SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH MM_USERS AS (
    SELECT DISTINCT
        FU.USER_ID,
        BR.ORGANIZATION_ID
    FROM APPS.FND_USER FU
    JOIN BOM.BOM_RESOURCE_EMPLOYEES BRE
        ON BRE.PERSON_ID = FU.EMPLOYEE_ID
    JOIN BOM.BOM_RESOURCES BR
        ON BR.RESOURCE_ID = BRE.RESOURCE_ID
       AND BR.ORGANIZATION_ID = BRE.ORGANIZATION_ID
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = BR.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND BR.RESOURCE_CODE LIKE 'MM%'
),
POSTED_TIME AS (
    SELECT
        EWO.ASSET_NUMBER,
        MAX(EWO.ASSET_DESCRIPTION) AS ASSET_DESCRIPTION,
        COUNT(DISTINCT EWO.WIP_ENTITY_ID) AS WORK_ORDERS_WITH_POSTED_TIME,
        COUNT(DISTINCT TO_CHAR(EWO.WIP_ENTITY_ID) || ':' || TO_CHAR(WT.OPERATION_SEQ_NUM)) AS POSTED_OPERATION_COUNT,
        COUNT(WT.ROWID) AS POSTED_TIME_TRANSACTION_COUNT,
        SUM(WT.TRANSACTION_QUANTITY) AS POSTED_HOURS,
        SUM(CASE WHEN MU.USER_ID IS NOT NULL THEN WT.TRANSACTION_QUANTITY ELSE 0 END) AS MM_POSTED_HOURS,
        SUM(CASE WHEN MU.USER_ID IS NULL THEN WT.TRANSACTION_QUANTITY ELSE 0 END) AS OTHER_POSTED_HOURS,
        SUM(
            WT.TRANSACTION_QUANTITY
            * NVL(WT.ACTUAL_RESOURCE_RATE, NVL(WT.STANDARD_RESOURCE_RATE, NVL(WT.CURRENCY_ACTUAL_RESOURCE_RATE, 0)))
        ) AS POSTED_RESOURCE_COST,
        AVG(WT.TRANSACTION_QUANTITY) AS AVG_POSTED_HOURS_PER_TRANSACTION,
        MAX(WT.TRANSACTION_QUANTITY) AS MAX_SINGLE_POSTED_TRANSACTION,
        MIN(WT.TRANSACTION_DATE) AS FIRST_POSTED_TIME_DATE,
        MAX(WT.TRANSACTION_DATE) AS LAST_POSTED_TIME_DATE
    FROM WIP.WIP_TRANSACTIONS WT
    JOIN APPS.EAM_WORK_ORDERS_V EWO
        ON EWO.WIP_ENTITY_ID = WT.WIP_ENTITY_ID
       AND EWO.ORGANIZATION_ID = WT.ORGANIZATION_ID
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    JOIN BOM.BOM_RESOURCES BR
        ON BR.RESOURCE_ID = WT.RESOURCE_ID
       AND BR.ORGANIZATION_ID = WT.ORGANIZATION_ID
    LEFT JOIN MM_USERS MU
        ON MU.USER_ID = WT.CREATED_BY
       AND MU.ORGANIZATION_ID = WT.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND EWO.ASSET_NUMBER IS NOT NULL
      AND UPPER(EWO.ASSET_NUMBER) NOT IN ('TECHNICAL TRAINING', 'MACHINE SHOP')
      AND WT.TRANSACTION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
      AND BR.UNIT_OF_MEASURE = 'HR'
    GROUP BY EWO.ASSET_NUMBER
),
PENDING_TIME AS (
    SELECT
        EWO.ASSET_NUMBER,
        MAX(EWO.ASSET_DESCRIPTION) AS ASSET_DESCRIPTION,
        COUNT(DISTINCT EWO.WIP_ENTITY_ID) AS WORK_ORDERS_WITH_PENDING_TIME,
        COUNT(DISTINCT TO_CHAR(EWO.WIP_ENTITY_ID) || ':' || TO_CHAR(WCTI.OPERATION_SEQ_NUM)) AS PENDING_OPERATION_COUNT,
        COUNT(WCTI.TRANSACTION_ID) AS PENDING_TIME_TRANSACTION_COUNT,
        SUM(WCTI.TRANSACTION_QUANTITY) AS PENDING_HOURS,
        SUM(CASE WHEN MU.USER_ID IS NOT NULL THEN WCTI.TRANSACTION_QUANTITY ELSE 0 END) AS MM_PENDING_HOURS,
        SUM(CASE WHEN MU.USER_ID IS NULL THEN WCTI.TRANSACTION_QUANTITY ELSE 0 END) AS OTHER_PENDING_HOURS,
        SUM(
            WCTI.TRANSACTION_QUANTITY
            * NVL(WCTI.ACTUAL_RESOURCE_RATE, NVL(WCTI.CURRENCY_ACTUAL_RESOURCE_RATE, 0))
        ) AS PENDING_RESOURCE_COST,
        AVG(WCTI.TRANSACTION_QUANTITY) AS AVG_PENDING_HOURS_PER_TRANSACTION,
        MAX(WCTI.TRANSACTION_QUANTITY) AS MAX_SINGLE_PENDING_TRANSACTION,
        MIN(WCTI.TRANSACTION_DATE) AS FIRST_PENDING_TIME_DATE,
        MAX(WCTI.TRANSACTION_DATE) AS LAST_PENDING_TIME_DATE
    FROM WIP.WIP_COST_TXN_INTERFACE WCTI
    JOIN APPS.EAM_WORK_ORDERS_V EWO
        ON EWO.WIP_ENTITY_ID = WCTI.WIP_ENTITY_ID
       AND EWO.ORGANIZATION_ID = WCTI.ORGANIZATION_ID
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    JOIN BOM.BOM_RESOURCES BR
        ON BR.RESOURCE_ID = WCTI.RESOURCE_ID
       AND BR.ORGANIZATION_ID = WCTI.ORGANIZATION_ID
    LEFT JOIN MM_USERS MU
        ON MU.USER_ID = WCTI.CREATED_BY
       AND MU.ORGANIZATION_ID = WCTI.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND EWO.ASSET_NUMBER IS NOT NULL
      AND UPPER(EWO.ASSET_NUMBER) NOT IN ('TECHNICAL TRAINING', 'MACHINE SHOP')
      AND WCTI.TRANSACTION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
      AND BR.UNIT_OF_MEASURE = 'HR'
    GROUP BY EWO.ASSET_NUMBER
),
TIME_ASSETS AS (
    SELECT
        COALESCE(PT.ASSET_NUMBER, PIT.ASSET_NUMBER) AS ASSET_NUMBER,
        COALESCE(PT.ASSET_DESCRIPTION, PIT.ASSET_DESCRIPTION) AS ASSET_DESCRIPTION,
        NVL(PT.WORK_ORDERS_WITH_POSTED_TIME, 0) AS WORK_ORDERS_WITH_POSTED_TIME,
        NVL(PT.POSTED_OPERATION_COUNT, 0) AS POSTED_OPERATION_COUNT,
        NVL(PT.POSTED_TIME_TRANSACTION_COUNT, 0) AS POSTED_TIME_TRANSACTION_COUNT,
        NVL(PT.POSTED_HOURS, 0) AS POSTED_HOURS,
        NVL(PT.MM_POSTED_HOURS, 0) AS MM_POSTED_HOURS,
        NVL(PT.OTHER_POSTED_HOURS, 0) AS OTHER_POSTED_HOURS,
        NVL(PT.POSTED_RESOURCE_COST, 0) AS POSTED_RESOURCE_COST,
        NVL(PT.AVG_POSTED_HOURS_PER_TRANSACTION, 0) AS AVG_POSTED_HOURS_PER_TRANSACTION,
        NVL(PT.MAX_SINGLE_POSTED_TRANSACTION, 0) AS MAX_SINGLE_POSTED_TRANSACTION,
        PT.FIRST_POSTED_TIME_DATE,
        PT.LAST_POSTED_TIME_DATE,
        NVL(PIT.WORK_ORDERS_WITH_PENDING_TIME, 0) AS WORK_ORDERS_WITH_PENDING_TIME,
        NVL(PIT.PENDING_OPERATION_COUNT, 0) AS PENDING_OPERATION_COUNT,
        NVL(PIT.PENDING_TIME_TRANSACTION_COUNT, 0) AS PENDING_TIME_TRANSACTION_COUNT,
        NVL(PIT.PENDING_HOURS, 0) AS PENDING_HOURS,
        NVL(PIT.MM_PENDING_HOURS, 0) AS MM_PENDING_HOURS,
        NVL(PIT.OTHER_PENDING_HOURS, 0) AS OTHER_PENDING_HOURS,
        NVL(PIT.PENDING_RESOURCE_COST, 0) AS PENDING_RESOURCE_COST,
        NVL(PIT.AVG_PENDING_HOURS_PER_TRANSACTION, 0) AS AVG_PENDING_HOURS_PER_TRANSACTION,
        NVL(PIT.MAX_SINGLE_PENDING_TRANSACTION, 0) AS MAX_SINGLE_PENDING_TRANSACTION,
        PIT.FIRST_PENDING_TIME_DATE,
        PIT.LAST_PENDING_TIME_DATE
    FROM POSTED_TIME PT
    FULL OUTER JOIN PENDING_TIME PIT
        ON PIT.ASSET_NUMBER = PT.ASSET_NUMBER
),
TOP_TIME_ASSETS AS (
    SELECT *
    FROM (
        SELECT
            TA.*,
            TA.POSTED_HOURS + TA.PENDING_HOURS AS ALL_TOTAL_ENTERED_HOURS,
            TA.MM_POSTED_HOURS + TA.MM_PENDING_HOURS AS ASSET_BURDEN_HOURS,
            TA.OTHER_POSTED_HOURS + TA.OTHER_PENDING_HOURS AS OTHER_TOTAL_ENTERED_HOURS
        FROM TIME_ASSETS TA
        ORDER BY
            TA.MM_POSTED_HOURS + TA.MM_PENDING_HOURS DESC,
            TA.ASSET_NUMBER
    )
    WHERE ROWNUM <= __LIMIT__
),
ASSET_WO AS (
    SELECT
        EWO.ASSET_NUMBER,
        COUNT(DISTINCT EWO.WIP_ENTITY_ID) AS TOTAL_WORK_ORDERS,
        COUNT(DISTINCT CASE WHEN EWO.WORK_ORDER_TYPE_DISP = 'DM' THEN EWO.WIP_ENTITY_ID END) AS DM_WORK_ORDERS,
        COUNT(DISTINCT CASE WHEN EWO.WIP_ENTITY_NAME LIKE 'PM%' THEN EWO.WIP_ENTITY_ID END) AS PM_WORK_ORDERS
    FROM APPS.EAM_WORK_ORDERS_V EWO
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    JOIN TOP_TIME_ASSETS TA
        ON TA.ASSET_NUMBER = EWO.ASSET_NUMBER
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND EWO.CREATION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
    GROUP BY EWO.ASSET_NUMBER
),
ASSET_PARTS AS (
    SELECT
        EWO.ASSET_NUMBER,
        COUNT(MMT.TRANSACTION_ID) AS TOTAL_PART_TRANSACTIONS,
        SUM(ABS(MMT.TRANSACTION_QUANTITY)) AS TOTAL_PARTS_CONSUMED,
        SUM(ABS(MMT.TRANSACTION_QUANTITY) * NVL(MMT.TRANSACTION_COST, MMT.ACTUAL_COST)) AS TOTAL_MATERIAL_COST
    FROM APPS.EAM_WORK_ORDERS_V EWO
    JOIN INV.MTL_MATERIAL_TRANSACTIONS MMT
        ON MMT.TRANSACTION_SOURCE_ID = EWO.WIP_ENTITY_ID
       AND MMT.ORGANIZATION_ID = EWO.ORGANIZATION_ID
       AND MMT.TRANSACTION_SOURCE_TYPE_ID = 5
       AND MMT.TRANSACTION_QUANTITY < 0
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    JOIN TOP_TIME_ASSETS TA
        ON TA.ASSET_NUMBER = EWO.ASSET_NUMBER
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND MMT.TRANSACTION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
    GROUP BY EWO.ASSET_NUMBER
)
SELECT
    TA.ASSET_NUMBER,
    TA.ASSET_DESCRIPTION,
    NVL(AW.TOTAL_WORK_ORDERS, 0) AS TOTAL_WORK_ORDERS,
    NVL(AW.DM_WORK_ORDERS, 0) AS DM_WORK_ORDERS,
    NVL(AW.PM_WORK_ORDERS, 0) AS PM_WORK_ORDERS,
    NVL(AP.TOTAL_PART_TRANSACTIONS, 0) AS TOTAL_PART_TRANSACTIONS,
    NVL(AP.TOTAL_PARTS_CONSUMED, 0) AS TOTAL_PARTS_CONSUMED,
    NVL(AP.TOTAL_MATERIAL_COST, 0) AS TOTAL_MATERIAL_COST,
    TA.WORK_ORDERS_WITH_POSTED_TIME,
    TA.POSTED_OPERATION_COUNT,
    TA.POSTED_TIME_TRANSACTION_COUNT,
    TA.POSTED_HOURS,
    TA.MM_POSTED_HOURS,
    TA.OTHER_POSTED_HOURS,
    TA.POSTED_RESOURCE_COST,
    TA.AVG_POSTED_HOURS_PER_TRANSACTION,
    TA.MAX_SINGLE_POSTED_TRANSACTION,
    TO_CHAR(TA.FIRST_POSTED_TIME_DATE, 'MM/DD/YYYY HH24:MI:SS') AS FIRST_POSTED_TIME_DATE,
    TO_CHAR(TA.LAST_POSTED_TIME_DATE, 'MM/DD/YYYY HH24:MI:SS') AS LAST_POSTED_TIME_DATE,
    TA.WORK_ORDERS_WITH_PENDING_TIME,
    TA.PENDING_OPERATION_COUNT,
    TA.PENDING_TIME_TRANSACTION_COUNT,
    TA.PENDING_HOURS,
    TA.MM_PENDING_HOURS,
    TA.OTHER_PENDING_HOURS,
    TA.PENDING_RESOURCE_COST,
    TA.AVG_PENDING_HOURS_PER_TRANSACTION,
    TA.MAX_SINGLE_PENDING_TRANSACTION,
    TO_CHAR(TA.FIRST_PENDING_TIME_DATE, 'MM/DD/YYYY HH24:MI:SS') AS FIRST_PENDING_TIME_DATE,
    TO_CHAR(TA.LAST_PENDING_TIME_DATE, 'MM/DD/YYYY HH24:MI:SS') AS LAST_PENDING_TIME_DATE,
    TA.ASSET_BURDEN_HOURS,
    TA.OTHER_TOTAL_ENTERED_HOURS,
    TA.ALL_TOTAL_ENTERED_HOURS,
    TA.POSTED_RESOURCE_COST + TA.PENDING_RESOURCE_COST AS TOTAL_RESOURCE_COST,
    NVL(AP.TOTAL_MATERIAL_COST, 0) + TA.POSTED_RESOURCE_COST + TA.PENDING_RESOURCE_COST AS TOTAL_ESTIMATED_COST,
    CASE
        WHEN TA.MAX_SINGLE_POSTED_TRANSACTION >= 24
          OR TA.MAX_SINGLE_PENDING_TRANSACTION >= 24
        THEN 'Y'
        ELSE 'N'
    END AS HAS_LARGE_TIME_TRANSACTION,
    RANK() OVER (ORDER BY NVL(AW.TOTAL_WORK_ORDERS, 0) DESC) AS RANK_BY_WORK_ORDERS,
    RANK() OVER (ORDER BY NVL(AP.TOTAL_PARTS_CONSUMED, 0) DESC) AS RANK_BY_PARTS,
    RANK() OVER (ORDER BY NVL(AP.TOTAL_MATERIAL_COST, 0) DESC) AS RANK_BY_MATERIAL_COST,
    RANK() OVER (ORDER BY TA.ASSET_BURDEN_HOURS DESC) AS RANK_BY_ASSET_BURDEN_HOURS
FROM TOP_TIME_ASSETS TA
LEFT JOIN ASSET_WO AW
    ON AW.ASSET_NUMBER = TA.ASSET_NUMBER
LEFT JOIN ASSET_PARTS AP
    ON AP.ASSET_NUMBER = TA.ASSET_NUMBER
ORDER BY
    TA.ASSET_BURDEN_HOURS DESC,
    NVL(AW.TOTAL_WORK_ORDERS, 0) DESC,
    TA.ASSET_NUMBER;

SPOOL OFF
EXIT
