SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH LATEST_QA AS (
    SELECT
        QR.ORGANIZATION_ID,
        QR.WORK_ORDER_ID,
        FU.EMPLOYEE_ID AS TECHNICIAN_PERSON_ID,
        COALESCE(PEO.FULL_NAME, FU.DESCRIPTION, FU.USER_NAME) AS TECHNICIAN,
        FU.USER_NAME AS BADGE_NUMBER,
        QP.NAME AS QA_PLAN_NAME,
        TO_CHAR(QR.QA_CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS LAST_INSPECTION_DATE,
        QR.CHARACTER2 AS QA_LOCATION,
        QR.COMMENT1 AS QA_DESCRIPTION_OF_WORK_PERFORMED,
        ROW_NUMBER() OVER (
            PARTITION BY QR.ORGANIZATION_ID, QR.WORK_ORDER_ID
            ORDER BY QR.QA_CREATION_DATE DESC, QR.QA_LAST_UPDATE_DATE DESC, QR.OCCURRENCE DESC
        ) AS RN
    FROM APPS.QA_RESULTS QR
    LEFT JOIN QA.QA_PLANS QP
        ON QP.PLAN_ID = QR.PLAN_ID
    LEFT JOIN APPS.FND_USER FU
        ON FU.USER_ID = QR.QA_CREATED_BY
    LEFT JOIN APPS.PER_ALL_PEOPLE_F PEO
        ON PEO.PERSON_ID = FU.EMPLOYEE_ID
       AND SYSDATE BETWEEN PEO.EFFECTIVE_START_DATE AND PEO.EFFECTIVE_END_DATE
    WHERE QR.MAINTENANCE_OP_SEQ = 10
),
OP10_COMPLETER AS (
    SELECT
        WO.ORGANIZATION_ID,
        WO.WIP_ENTITY_ID,
        FU.EMPLOYEE_ID AS OP10_COMPLETED_BY_PERSON_ID,
        COALESCE(PEO.FULL_NAME, FU.DESCRIPTION, FU.USER_NAME) AS OP10_COMPLETED_BY,
        FU.USER_NAME AS OP10_COMPLETED_BY_BADGE,
        TO_CHAR(WO.LAST_UPDATE_DATE, 'MM/DD/YYYY HH24:MI:SS') AS OP10_COMPLETED_DATE
    FROM APPS.WIP_OPERATIONS_V WO
    LEFT JOIN APPS.FND_USER FU
        ON FU.USER_ID = WO.LAST_UPDATED_BY
    LEFT JOIN APPS.PER_ALL_PEOPLE_F PEO
        ON PEO.PERSON_ID = FU.EMPLOYEE_ID
       AND WO.LAST_UPDATE_DATE BETWEEN PEO.EFFECTIVE_START_DATE AND PEO.EFFECTIVE_END_DATE
    WHERE WO.OPERATION_SEQ_NUM = 10
      AND WO.OPERATION_COMPLETED = 'Y'
),
TECH_RESOURCE AS (
    SELECT
        BRE.PERSON_ID,
        LISTAGG(DISTINCT BR.RESOURCE_CODE, ', ') WITHIN GROUP (ORDER BY BR.RESOURCE_CODE) AS TECHNICIAN_RESOURCE_CODE,
        LISTAGG(DISTINCT BR.DESCRIPTION, ', ') WITHIN GROUP (ORDER BY BR.RESOURCE_CODE) AS TECHNICIAN_RESOURCE_DESCRIPTION
    FROM BOM.BOM_RESOURCE_EMPLOYEES BRE
    JOIN BOM.BOM_RESOURCES BR
        ON BR.RESOURCE_ID = BRE.RESOURCE_ID
       AND BR.ORGANIZATION_ID = BRE.ORGANIZATION_ID
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = BR.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND SYSDATE BETWEEN BRE.EFFECTIVE_START_DATE AND BRE.EFFECTIVE_END_DATE
      AND BR.RESOURCE_CODE LIKE 'MM%'
    GROUP BY BRE.PERSON_ID
),
WO_PARTS AS (
    SELECT
        EWO.ORGANIZATION_ID,
        EWO.WIP_ENTITY_ID,
        COUNT(MMT.TRANSACTION_ID) AS PART_TRANSACTION_COUNT,
        COUNT(DISTINCT MMT.INVENTORY_ITEM_ID) AS DISTINCT_PARTS_USED,
        SUM(ABS(MMT.TRANSACTION_QUANTITY)) AS TOTAL_PARTS_CONSUMED,
        SUM(ABS(MMT.TRANSACTION_QUANTITY) * NVL(MMT.TRANSACTION_COST, MMT.ACTUAL_COST)) AS TOTAL_MATERIAL_COST
    FROM APPS.EAM_WORK_ORDERS_V EWO
    JOIN INV.MTL_MATERIAL_TRANSACTIONS MMT
        ON MMT.TRANSACTION_SOURCE_ID = EWO.WIP_ENTITY_ID
       AND MMT.ORGANIZATION_ID = EWO.ORGANIZATION_ID
       AND MMT.TRANSACTION_SOURCE_TYPE_ID = 5
       AND MMT.TRANSACTION_QUANTITY < 0
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND EWO.ASSET_NUMBER = __ASSET_NUMBER__
      AND MMT.TRANSACTION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
    GROUP BY EWO.ORGANIZATION_ID, EWO.WIP_ENTITY_ID
),
POSTED_TIME AS (
    SELECT
        EWO.ORGANIZATION_ID,
        EWO.WIP_ENTITY_ID,
        COUNT(DISTINCT TO_CHAR(WT.OPERATION_SEQ_NUM) || ':' || TO_CHAR(WT.RESOURCE_SEQ_NUM)) AS POSTED_RESOURCE_LINE_COUNT,
        COUNT(WT.ROWID) AS POSTED_TIME_TRANSACTION_COUNT,
        SUM(WT.TRANSACTION_QUANTITY) AS POSTED_HOURS,
        SUM(CASE WHEN WT.OPERATION_SEQ_NUM = 10 THEN WT.TRANSACTION_QUANTITY ELSE 0 END) AS OP10_POSTED_HOURS,
        MAX(WT.TRANSACTION_QUANTITY) AS MAX_SINGLE_POSTED_TRANSACTION,
        MIN(WT.TRANSACTION_DATE) AS FIRST_POSTED_TIME_DATE,
        MAX(WT.TRANSACTION_DATE) AS LAST_POSTED_TIME_DATE
    FROM WIP.WIP_TRANSACTIONS WT
    JOIN APPS.EAM_WORK_ORDERS_V EWO
        ON EWO.WIP_ENTITY_ID = WT.WIP_ENTITY_ID
       AND EWO.ORGANIZATION_ID = WT.ORGANIZATION_ID
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    LEFT JOIN BOM.BOM_RESOURCES BR
        ON BR.RESOURCE_ID = WT.RESOURCE_ID
       AND BR.ORGANIZATION_ID = WT.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND EWO.ASSET_NUMBER = __ASSET_NUMBER__
      AND WT.TRANSACTION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
      AND BR.UNIT_OF_MEASURE = 'HR'
    GROUP BY EWO.ORGANIZATION_ID, EWO.WIP_ENTITY_ID
),
PENDING_TIME AS (
    SELECT
        EWO.ORGANIZATION_ID,
        EWO.WIP_ENTITY_ID,
        COUNT(DISTINCT TO_CHAR(WCTI.OPERATION_SEQ_NUM) || ':' || TO_CHAR(WCTI.RESOURCE_SEQ_NUM)) AS PENDING_RESOURCE_LINE_COUNT,
        COUNT(WCTI.TRANSACTION_ID) AS PENDING_TIME_TRANSACTION_COUNT,
        SUM(WCTI.TRANSACTION_QUANTITY) AS PENDING_HOURS,
        SUM(CASE WHEN WCTI.OPERATION_SEQ_NUM = 10 THEN WCTI.TRANSACTION_QUANTITY ELSE 0 END) AS OP10_PENDING_HOURS,
        MAX(WCTI.TRANSACTION_QUANTITY) AS MAX_SINGLE_PENDING_TRANSACTION,
        MIN(WCTI.TRANSACTION_DATE) AS FIRST_PENDING_TIME_DATE,
        MAX(WCTI.TRANSACTION_DATE) AS LAST_PENDING_TIME_DATE
    FROM WIP.WIP_COST_TXN_INTERFACE WCTI
    JOIN APPS.EAM_WORK_ORDERS_V EWO
        ON EWO.WIP_ENTITY_ID = WCTI.WIP_ENTITY_ID
       AND EWO.ORGANIZATION_ID = WCTI.ORGANIZATION_ID
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    LEFT JOIN BOM.BOM_RESOURCES BR
        ON BR.RESOURCE_ID = WCTI.RESOURCE_ID
       AND BR.ORGANIZATION_ID = WCTI.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND EWO.ASSET_NUMBER = __ASSET_NUMBER__
      AND WCTI.TRANSACTION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
      AND BR.UNIT_OF_MEASURE = 'HR'
    GROUP BY EWO.ORGANIZATION_ID, EWO.WIP_ENTITY_ID
),
RESOURCE_ROLLUP AS (
    SELECT
        EWO.ORGANIZATION_ID,
        EWO.WIP_ENTITY_ID,
        SUM(WOR.USAGE_RATE_OR_AMOUNT) AS PLANNED_HOURS,
        SUM(WOR.APPLIED_RESOURCE_UNITS) AS APPLIED_HOURS
    FROM WIP.WIP_OPERATION_RESOURCES WOR
    JOIN APPS.EAM_WORK_ORDERS_V EWO
        ON EWO.WIP_ENTITY_ID = WOR.WIP_ENTITY_ID
       AND EWO.ORGANIZATION_ID = WOR.ORGANIZATION_ID
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    LEFT JOIN BOM.BOM_RESOURCES BR
        ON BR.RESOURCE_ID = WOR.RESOURCE_ID
       AND BR.ORGANIZATION_ID = WOR.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND EWO.ASSET_NUMBER = __ASSET_NUMBER__
      AND EWO.CREATION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
      AND BR.UNIT_OF_MEASURE = 'HR'
    GROUP BY EWO.ORGANIZATION_ID, EWO.WIP_ENTITY_ID
),
OP10_DEPT AS (
    SELECT
        WO.ORGANIZATION_ID,
        WO.WIP_ENTITY_ID,
        BD.DEPARTMENT_CODE AS PRIMARY_DEPARTMENT_CODE,
        BD.DESCRIPTION AS PRIMARY_DEPARTMENT_DESCRIPTION
    FROM APPS.WIP_OPERATIONS_V WO
    LEFT JOIN BOM.BOM_DEPARTMENTS BD
        ON BD.DEPARTMENT_ID = WO.DEPARTMENT_ID
       AND BD.ORGANIZATION_ID = WO.ORGANIZATION_ID
    WHERE WO.OPERATION_SEQ_NUM = 10
)
SELECT
    EWO.WIP_ENTITY_NAME AS WORK_ORDER,
    EWO.WORK_ORDER_STATUS,
    EWO.WORK_ORDER_TYPE_DISP AS WO_TYPE,
    EWO.ASSET_NUMBER,
    EWO.ASSET_DESCRIPTION,
    EWO.ASSET_ACTIVITY,
    EWO.DESCRIPTION AS WO_DESCRIPTION,
    TO_CHAR(EWO.CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS WO_CREATED,
    TO_CHAR(EWO.SCHEDULED_START_DATE, 'MM/DD/YYYY') AS SCHEDULED_START,
    OP10.PRIMARY_DEPARTMENT_CODE,
    OP10.PRIMARY_DEPARTMENT_DESCRIPTION,
    COALESCE(OC.OP10_COMPLETED_BY, LQ.TECHNICIAN) AS TECHNICIAN,
    COALESCE(OC.OP10_COMPLETED_BY_BADGE, LQ.BADGE_NUMBER) AS BADGE_NUMBER,
    TR.TECHNICIAN_RESOURCE_CODE,
    TR.TECHNICIAN_RESOURCE_DESCRIPTION,
    OC.OP10_COMPLETED_BY,
    OC.OP10_COMPLETED_BY_BADGE,
    OC.OP10_COMPLETED_DATE,
    LQ.QA_PLAN_NAME,
    LQ.LAST_INSPECTION_DATE,
    LQ.QA_LOCATION,
    LQ.QA_DESCRIPTION_OF_WORK_PERFORMED,
    NVL(RR.PLANNED_HOURS, 0) AS PLANNED_HOURS,
    NVL(RR.APPLIED_HOURS, 0) AS APPLIED_HOURS,
    NVL(PT.POSTED_RESOURCE_LINE_COUNT, 0) AS POSTED_RESOURCE_LINE_COUNT,
    NVL(PT.POSTED_TIME_TRANSACTION_COUNT, 0) AS POSTED_TIME_TRANSACTION_COUNT,
    NVL(PT.OP10_POSTED_HOURS, 0) AS OP10_POSTED_HOURS,
    NVL(PT.POSTED_HOURS, 0) AS POSTED_HOURS,
    TO_CHAR(PT.FIRST_POSTED_TIME_DATE, 'MM/DD/YYYY HH24:MI:SS') AS FIRST_POSTED_TIME_DATE,
    TO_CHAR(PT.LAST_POSTED_TIME_DATE, 'MM/DD/YYYY HH24:MI:SS') AS LAST_POSTED_TIME_DATE,
    NVL(PIT.PENDING_RESOURCE_LINE_COUNT, 0) AS PENDING_RESOURCE_LINE_COUNT,
    NVL(PIT.PENDING_TIME_TRANSACTION_COUNT, 0) AS PENDING_TIME_TRANSACTION_COUNT,
    NVL(PIT.OP10_PENDING_HOURS, 0) AS OP10_PENDING_HOURS,
    NVL(PIT.PENDING_HOURS, 0) AS PENDING_HOURS,
    TO_CHAR(PIT.FIRST_PENDING_TIME_DATE, 'MM/DD/YYYY HH24:MI:SS') AS FIRST_PENDING_TIME_DATE,
    TO_CHAR(PIT.LAST_PENDING_TIME_DATE, 'MM/DD/YYYY HH24:MI:SS') AS LAST_PENDING_TIME_DATE,
    NVL(PT.POSTED_HOURS, 0) + NVL(PIT.PENDING_HOURS, 0) AS ALL_TOTAL_ENTERED_HOURS,
    CASE
        WHEN NVL(PT.MAX_SINGLE_POSTED_TRANSACTION, 0) >= 24
          OR NVL(PIT.MAX_SINGLE_PENDING_TRANSACTION, 0) >= 24
        THEN 'Y'
        ELSE 'N'
    END AS HAS_LARGE_TIME_TRANSACTION,
    NVL(WP.PART_TRANSACTION_COUNT, 0) AS PART_TRANSACTION_COUNT,
    NVL(WP.DISTINCT_PARTS_USED, 0) AS DISTINCT_PARTS_USED,
    NVL(WP.TOTAL_PARTS_CONSUMED, 0) AS TOTAL_PARTS_CONSUMED,
    NVL(WP.TOTAL_MATERIAL_COST, 0) AS TOTAL_MATERIAL_COST
FROM APPS.EAM_WORK_ORDERS_V EWO
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
LEFT JOIN LATEST_QA LQ
    ON LQ.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND LQ.WORK_ORDER_ID = EWO.WIP_ENTITY_ID
   AND LQ.RN = 1
LEFT JOIN OP10_COMPLETER OC
    ON OC.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND OC.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
LEFT JOIN TECH_RESOURCE TR
    ON TR.PERSON_ID = COALESCE(OC.OP10_COMPLETED_BY_PERSON_ID, LQ.TECHNICIAN_PERSON_ID)
LEFT JOIN WO_PARTS WP
    ON WP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND WP.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
LEFT JOIN POSTED_TIME PT
    ON PT.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND PT.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
LEFT JOIN PENDING_TIME PIT
    ON PIT.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND PIT.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
LEFT JOIN RESOURCE_ROLLUP RR
    ON RR.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND RR.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
LEFT JOIN OP10_DEPT OP10
    ON OP10.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND OP10.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
  AND EWO.ASSET_NUMBER = __ASSET_NUMBER__
  AND EWO.CREATION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
ORDER BY ALL_TOTAL_ENTERED_HOURS DESC, EWO.CREATION_DATE DESC, EWO.WIP_ENTITY_NAME DESC;
