SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH ASSET_WO AS (
    SELECT
        EWO.ASSET_NUMBER,
        EWO.ASSET_DESCRIPTION,
        COUNT(DISTINCT EWO.WIP_ENTITY_ID) AS TOTAL_WORK_ORDERS,
        SUM(CASE WHEN EWO.WORK_ORDER_TYPE_DISP = 'DM' THEN 1 ELSE 0 END) AS DM_WORK_ORDERS,
        SUM(CASE WHEN EWO.WIP_ENTITY_NAME LIKE 'PM%' THEN 1 ELSE 0 END) AS PM_WORK_ORDERS
    FROM APPS.EAM_WORK_ORDERS_V EWO
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND EWO.ASSET_NUMBER IS NOT NULL
      AND EWO.CREATION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
    GROUP BY EWO.ASSET_NUMBER, EWO.ASSET_DESCRIPTION
),
ASSET_PARTS AS (
    SELECT
        EWO.ASSET_NUMBER,
        COUNT(MMT.TRANSACTION_ID) AS TOTAL_PART_TRANSACTIONS,
        SUM(ABS(MMT.TRANSACTION_QUANTITY)) AS TOTAL_PARTS_CONSUMED
    FROM APPS.EAM_WORK_ORDERS_V EWO
    JOIN INV.MTL_MATERIAL_TRANSACTIONS MMT
        ON MMT.TRANSACTION_SOURCE_ID = EWO.WIP_ENTITY_ID
       AND MMT.ORGANIZATION_ID = EWO.ORGANIZATION_ID
       AND MMT.TRANSACTION_SOURCE_TYPE_ID = 5
       AND MMT.TRANSACTION_QUANTITY < 0
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND MMT.TRANSACTION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
    GROUP BY EWO.ASSET_NUMBER
)
SELECT *
FROM (
    SELECT
        AW.ASSET_NUMBER,
        AW.ASSET_DESCRIPTION,
        AW.TOTAL_WORK_ORDERS,
        AW.DM_WORK_ORDERS,
        AW.PM_WORK_ORDERS,
        NVL(AP.TOTAL_PART_TRANSACTIONS, 0) AS TOTAL_PART_TRANSACTIONS,
        NVL(AP.TOTAL_PARTS_CONSUMED, 0) AS TOTAL_PARTS_CONSUMED,
        RANK() OVER (ORDER BY AW.TOTAL_WORK_ORDERS DESC) AS RANK_BY_WO,
        RANK() OVER (ORDER BY NVL(AP.TOTAL_PARTS_CONSUMED, 0) DESC) AS RANK_BY_PARTS
    FROM ASSET_WO AW
    LEFT JOIN ASSET_PARTS AP
        ON AP.ASSET_NUMBER = AW.ASSET_NUMBER
    ORDER BY AW.TOTAL_WORK_ORDERS DESC
)
WHERE ROWNUM <= __LIMIT__;

SPOOL OFF
EXIT
