SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH MM_USERS AS (
    SELECT DISTINCT
        FU.USER_ID,
        BR.ORGANIZATION_ID
    FROM APPS.FND_USER FU
    JOIN BOM.BOM_RESOURCE_EMPLOYEES BRE
        ON BRE.PERSON_ID = FU.EMPLOYEE_ID
    JOIN BOM.BOM_RESOURCES BR
        ON BR.RESOURCE_ID = BRE.RESOURCE_ID
       AND BR.ORGANIZATION_ID = BRE.ORGANIZATION_ID
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = BR.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND BR.RESOURCE_CODE LIKE 'MM%'
),
LATEST_QA AS (
    SELECT
        QR.ORGANIZATION_ID,
        QR.WORK_ORDER_ID,
        FU.EMPLOYEE_ID AS TECHNICIAN_PERSON_ID,
        COALESCE(PEO.FULL_NAME, FU.DESCRIPTION, FU.USER_NAME) AS TECHNICIAN,
        FU.USER_NAME AS BADGE_NUMBER,
        TO_CHAR(QR.QA_CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS LAST_INSPECTION_DATE,
        ROW_NUMBER() OVER (
            PARTITION BY QR.ORGANIZATION_ID, QR.WORK_ORDER_ID
            ORDER BY QR.QA_CREATION_DATE DESC, QR.QA_LAST_UPDATE_DATE DESC, QR.OCCURRENCE DESC
        ) AS RN
    FROM APPS.QA_RESULTS QR
    LEFT JOIN APPS.FND_USER FU
        ON FU.USER_ID = QR.QA_CREATED_BY
    LEFT JOIN APPS.PER_ALL_PEOPLE_F PEO
        ON PEO.PERSON_ID = FU.EMPLOYEE_ID
       AND SYSDATE BETWEEN PEO.EFFECTIVE_START_DATE AND PEO.EFFECTIVE_END_DATE
    WHERE QR.MAINTENANCE_OP_SEQ = 10
),
OP10_COMPLETER AS (
    SELECT
        WO.ORGANIZATION_ID,
        WO.WIP_ENTITY_ID,
        FU.EMPLOYEE_ID AS OP10_COMPLETED_BY_PERSON_ID,
        COALESCE(PEO.FULL_NAME, FU.DESCRIPTION, FU.USER_NAME) AS OP10_COMPLETED_BY,
        FU.USER_NAME AS OP10_COMPLETED_BY_BADGE,
        TO_CHAR(WO.LAST_UPDATE_DATE, 'MM/DD/YYYY HH24:MI:SS') AS OP10_COMPLETED_DATE
    FROM APPS.WIP_OPERATIONS_V WO
    LEFT JOIN APPS.FND_USER FU
        ON FU.USER_ID = WO.LAST_UPDATED_BY
    LEFT JOIN APPS.PER_ALL_PEOPLE_F PEO
        ON PEO.PERSON_ID = FU.EMPLOYEE_ID
       AND WO.LAST_UPDATE_DATE BETWEEN PEO.EFFECTIVE_START_DATE AND PEO.EFFECTIVE_END_DATE
    WHERE WO.OPERATION_SEQ_NUM = 10
      AND WO.OPERATION_COMPLETED = 'Y'
),
TECH_RESOURCE AS (
    SELECT
        BRE.PERSON_ID,
        LISTAGG(DISTINCT BR.RESOURCE_CODE, ', ') WITHIN GROUP (ORDER BY BR.RESOURCE_CODE) AS TECHNICIAN_RESOURCE_CODE
    FROM BOM.BOM_RESOURCE_EMPLOYEES BRE
    JOIN BOM.BOM_RESOURCES BR
        ON BR.RESOURCE_ID = BRE.RESOURCE_ID
       AND BR.ORGANIZATION_ID = BRE.ORGANIZATION_ID
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = BR.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND SYSDATE BETWEEN BRE.EFFECTIVE_START_DATE AND BRE.EFFECTIVE_END_DATE
      AND BR.RESOURCE_CODE LIKE 'MM%'
    GROUP BY BRE.PERSON_ID
),
POSTED_TIME AS (
    SELECT
        WT.ORGANIZATION_ID,
        WT.WIP_ENTITY_ID,
        SUM(WT.TRANSACTION_QUANTITY) AS POSTED_HOURS,
        SUM(CASE WHEN MU.USER_ID IS NOT NULL THEN WT.TRANSACTION_QUANTITY ELSE 0 END) AS MM_POSTED_HOURS,
        SUM(CASE WHEN MU.USER_ID IS NULL THEN WT.TRANSACTION_QUANTITY ELSE 0 END) AS OTHER_POSTED_HOURS,
        MIN(WT.TRANSACTION_DATE) AS FIRST_POSTED_TIME_DATE,
        MAX(WT.TRANSACTION_DATE) AS LAST_POSTED_TIME_DATE
    FROM WIP.WIP_TRANSACTIONS WT
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = WT.ORGANIZATION_ID
    JOIN BOM.BOM_RESOURCES BR
        ON BR.RESOURCE_ID = WT.RESOURCE_ID
       AND BR.ORGANIZATION_ID = WT.ORGANIZATION_ID
    LEFT JOIN MM_USERS MU
        ON MU.USER_ID = WT.CREATED_BY
       AND MU.ORGANIZATION_ID = WT.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND WT.TRANSACTION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
      AND BR.UNIT_OF_MEASURE = 'HR'
    GROUP BY WT.ORGANIZATION_ID, WT.WIP_ENTITY_ID
),
PENDING_TIME AS (
    SELECT
        WCTI.ORGANIZATION_ID,
        WCTI.WIP_ENTITY_ID,
        SUM(WCTI.TRANSACTION_QUANTITY) AS PENDING_HOURS,
        SUM(CASE WHEN MU.USER_ID IS NOT NULL THEN WCTI.TRANSACTION_QUANTITY ELSE 0 END) AS MM_PENDING_HOURS,
        SUM(CASE WHEN MU.USER_ID IS NULL THEN WCTI.TRANSACTION_QUANTITY ELSE 0 END) AS OTHER_PENDING_HOURS,
        MIN(WCTI.TRANSACTION_DATE) AS FIRST_PENDING_TIME_DATE,
        MAX(WCTI.TRANSACTION_DATE) AS LAST_PENDING_TIME_DATE
    FROM WIP.WIP_COST_TXN_INTERFACE WCTI
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = WCTI.ORGANIZATION_ID
    JOIN BOM.BOM_RESOURCES BR
        ON BR.RESOURCE_ID = WCTI.RESOURCE_ID
       AND BR.ORGANIZATION_ID = WCTI.ORGANIZATION_ID
    LEFT JOIN MM_USERS MU
        ON MU.USER_ID = WCTI.CREATED_BY
       AND MU.ORGANIZATION_ID = WCTI.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND WCTI.TRANSACTION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
      AND BR.UNIT_OF_MEASURE = 'HR'
    GROUP BY WCTI.ORGANIZATION_ID, WCTI.WIP_ENTITY_ID
),
WO_TIME AS (
    SELECT
        COALESCE(PT.ORGANIZATION_ID, PIT.ORGANIZATION_ID) AS ORGANIZATION_ID,
        COALESCE(PT.WIP_ENTITY_ID, PIT.WIP_ENTITY_ID) AS WIP_ENTITY_ID,
        NVL(PT.MM_POSTED_HOURS, 0) + NVL(PIT.MM_PENDING_HOURS, 0) AS WO_MM_TIME_HOURS,
        NVL(PT.OTHER_POSTED_HOURS, 0) + NVL(PIT.OTHER_PENDING_HOURS, 0) AS WO_OTHER_TIME_HOURS,
        NVL(PT.POSTED_HOURS, 0) + NVL(PIT.PENDING_HOURS, 0) AS WO_ALL_TIME_HOURS,
        TO_CHAR(PT.FIRST_POSTED_TIME_DATE, 'MM/DD/YYYY HH24:MI:SS') AS FIRST_POSTED_TIME_DATE,
        TO_CHAR(PT.LAST_POSTED_TIME_DATE, 'MM/DD/YYYY HH24:MI:SS') AS LAST_POSTED_TIME_DATE,
        TO_CHAR(PIT.FIRST_PENDING_TIME_DATE, 'MM/DD/YYYY HH24:MI:SS') AS FIRST_PENDING_TIME_DATE,
        TO_CHAR(PIT.LAST_PENDING_TIME_DATE, 'MM/DD/YYYY HH24:MI:SS') AS LAST_PENDING_TIME_DATE
    FROM POSTED_TIME PT
    FULL OUTER JOIN PENDING_TIME PIT
        ON PIT.ORGANIZATION_ID = PT.ORGANIZATION_ID
       AND PIT.WIP_ENTITY_ID = PT.WIP_ENTITY_ID
),
PART_LINES AS (
    SELECT
        EWO.ASSET_NUMBER,
        EWO.ASSET_DESCRIPTION,
        EWO.WIP_ENTITY_ID,
        EWO.WIP_ENTITY_NAME AS WORK_ORDER,
        EWO.WORK_ORDER_STATUS,
        EWO.WORK_ORDER_TYPE_DISP AS WO_TYPE,
        TO_CHAR(EWO.CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS WO_CREATED,
        COALESCE(OC.OP10_COMPLETED_BY, LQ.TECHNICIAN) AS TECHNICIAN,
        COALESCE(OC.OP10_COMPLETED_BY_BADGE, LQ.BADGE_NUMBER) AS BADGE_NUMBER,
        TR.TECHNICIAN_RESOURCE_CODE,
        OC.OP10_COMPLETED_BY,
        OC.OP10_COMPLETED_BY_BADGE,
        OC.OP10_COMPLETED_DATE,
        LQ.LAST_INSPECTION_DATE,
        FU.USER_NAME AS PART_TRANSACTION_USER,
        MTT.TRANSACTION_TYPE_NAME AS TRANSACTION_TYPE,
        TO_CHAR(MMT.TRANSACTION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS PART_TRANSACTION_DATE,
        MMT.TRANSACTION_DATE,
        MSI.SEGMENT1 AS PART_NUMBER,
        MSI.DESCRIPTION AS PART_DESCRIPTION,
        MMT.TRANSACTION_QUANTITY AS QTY,
        ABS(MMT.TRANSACTION_QUANTITY) AS ABS_QTY,
        MMT.TRANSACTION_UOM AS UOM,
        NVL(MMT.TRANSACTION_COST, MMT.ACTUAL_COST) AS UNIT_MATERIAL_COST,
        ABS(MMT.TRANSACTION_QUANTITY) * NVL(MMT.TRANSACTION_COST, MMT.ACTUAL_COST) AS LINE_MATERIAL_COST,
        MMT.SUBINVENTORY_CODE AS FROM_SUBINVENTORY,
        MMT.TRANSACTION_REFERENCE AS REFERENCE,
        NVL(WT.WO_MM_TIME_HOURS, 0) AS WO_MM_TIME_HOURS,
        NVL(WT.WO_OTHER_TIME_HOURS, 0) AS WO_OTHER_TIME_HOURS,
        NVL(WT.WO_ALL_TIME_HOURS, 0) AS WO_ALL_TIME_HOURS,
        WT.FIRST_POSTED_TIME_DATE,
        WT.LAST_POSTED_TIME_DATE,
        WT.FIRST_PENDING_TIME_DATE,
        WT.LAST_PENDING_TIME_DATE
    FROM APPS.EAM_WORK_ORDERS_V EWO
    JOIN INV.MTL_MATERIAL_TRANSACTIONS MMT
        ON MMT.TRANSACTION_SOURCE_ID = EWO.WIP_ENTITY_ID
       AND MMT.ORGANIZATION_ID = EWO.ORGANIZATION_ID
       AND MMT.TRANSACTION_SOURCE_TYPE_ID = 5
       AND MMT.TRANSACTION_QUANTITY < 0
    JOIN INV.MTL_SYSTEM_ITEMS_B MSI
        ON MSI.INVENTORY_ITEM_ID = MMT.INVENTORY_ITEM_ID
       AND MSI.ORGANIZATION_ID = MMT.ORGANIZATION_ID
    JOIN INV.MTL_TRANSACTION_TYPES MTT
        ON MTT.TRANSACTION_TYPE_ID = MMT.TRANSACTION_TYPE_ID
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    LEFT JOIN APPS.FND_USER FU
        ON FU.USER_ID = MMT.CREATED_BY
    LEFT JOIN LATEST_QA LQ
        ON LQ.ORGANIZATION_ID = EWO.ORGANIZATION_ID
       AND LQ.WORK_ORDER_ID = EWO.WIP_ENTITY_ID
       AND LQ.RN = 1
    LEFT JOIN OP10_COMPLETER OC
        ON OC.ORGANIZATION_ID = EWO.ORGANIZATION_ID
       AND OC.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
    LEFT JOIN TECH_RESOURCE TR
        ON TR.PERSON_ID = COALESCE(OC.OP10_COMPLETED_BY_PERSON_ID, LQ.TECHNICIAN_PERSON_ID)
    LEFT JOIN WO_TIME WT
        ON WT.ORGANIZATION_ID = EWO.ORGANIZATION_ID
       AND WT.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND EWO.ASSET_NUMBER IN (__ASSET_NUMBERS__)
      AND MMT.TRANSACTION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
)
SELECT
    ASSET_NUMBER,
    ASSET_DESCRIPTION,
    PART_NUMBER,
    PART_DESCRIPTION,
    COUNT(*) OVER (PARTITION BY ASSET_NUMBER, PART_NUMBER) AS PART_FREQUENCY_ON_ASSET,
    SUM(ABS_QTY) OVER (PARTITION BY ASSET_NUMBER, PART_NUMBER) AS PART_QTY_ON_ASSET,
    SUM(LINE_MATERIAL_COST) OVER (PARTITION BY ASSET_NUMBER, PART_NUMBER) AS PART_MATERIAL_COST_ON_ASSET,
    COUNT(*) OVER (PARTITION BY PART_NUMBER) AS PART_FREQUENCY_ALL_SELECTED_ASSETS,
    SUM(ABS_QTY) OVER (PARTITION BY PART_NUMBER) AS PART_QTY_ALL_SELECTED_ASSETS,
    SUM(LINE_MATERIAL_COST) OVER (PARTITION BY PART_NUMBER) AS PART_MATERIAL_COST_ALL_SELECTED_ASSETS,
    WORK_ORDER,
    WORK_ORDER_STATUS,
    WO_TYPE,
    WO_CREATED,
    TECHNICIAN,
    BADGE_NUMBER,
    TECHNICIAN_RESOURCE_CODE,
    OP10_COMPLETED_BY,
    OP10_COMPLETED_BY_BADGE,
    OP10_COMPLETED_DATE,
    LAST_INSPECTION_DATE,
    PART_TRANSACTION_USER,
    TRANSACTION_TYPE,
    PART_TRANSACTION_DATE,
    QTY,
    ABS_QTY,
    UOM,
    UNIT_MATERIAL_COST,
    LINE_MATERIAL_COST,
    FROM_SUBINVENTORY,
    REFERENCE,
    WO_MM_TIME_HOURS,
    WO_OTHER_TIME_HOURS,
    WO_ALL_TIME_HOURS,
    FIRST_POSTED_TIME_DATE,
    LAST_POSTED_TIME_DATE,
    FIRST_PENDING_TIME_DATE,
    LAST_PENDING_TIME_DATE
FROM PART_LINES
ORDER BY
    PART_FREQUENCY_ALL_SELECTED_ASSETS DESC,
    PART_MATERIAL_COST_ALL_SELECTED_ASSETS DESC,
    PART_NUMBER,
    ASSET_NUMBER,
    TRANSACTION_DATE DESC,
    WORK_ORDER;

SPOOL OFF
EXIT
