SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    'POSTED' AS TIME_SOURCE,
    EWO.WIP_ENTITY_NAME AS WORK_ORDER,
    EWO.WORK_ORDER_STATUS,
    EWO.ASSET_NUMBER,
    EWO.ASSET_DESCRIPTION,
    EWO.DESCRIPTION AS WO_DESCRIPTION,
    WT.TRANSACTION_ID,
    TO_CHAR(WT.TRANSACTION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS TRANSACTION_DATE,
    WT.OPERATION_SEQ_NUM,
    WT.RESOURCE_SEQ_NUM,
    BR.RESOURCE_CODE,
    BR.DESCRIPTION AS RESOURCE_DESCRIPTION,
    BR.UNIT_OF_MEASURE AS RESOURCE_UOM,
    WT.TRANSACTION_QUANTITY,
    WT.TRANSACTION_UOM,
    WT.PRIMARY_QUANTITY,
    WT.PRIMARY_UOM,
    CREATED_USER.USER_NAME AS CREATED_BY_USER,
    COALESCE(CREATED_PERSON.FULL_NAME, CREATED_USER.DESCRIPTION, CREATED_USER.USER_NAME) AS CREATED_BY_NAME,
    UPDATED_USER.USER_NAME AS LAST_UPDATED_BY_USER,
    COALESCE(UPDATED_PERSON.FULL_NAME, UPDATED_USER.DESCRIPTION, UPDATED_USER.USER_NAME) AS LAST_UPDATED_BY_NAME,
    CAST(NULL AS NUMBER) AS PROCESS_PHASE,
    CAST(NULL AS VARCHAR2(30)) AS PROCESS_PHASE_MEANING,
    CAST(NULL AS NUMBER) AS PROCESS_STATUS,
    CAST(NULL AS VARCHAR2(30)) AS PROCESS_STATUS_MEANING,
    CASE
        WHEN WT.TRANSACTION_QUANTITY >= 24 THEN 'Y'
        ELSE 'N'
    END AS IS_LARGE_TIME_TRANSACTION
FROM WIP.WIP_TRANSACTIONS WT
JOIN APPS.EAM_WORK_ORDERS_V EWO
    ON EWO.WIP_ENTITY_ID = WT.WIP_ENTITY_ID
   AND EWO.ORGANIZATION_ID = WT.ORGANIZATION_ID
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
LEFT JOIN BOM.BOM_RESOURCES BR
    ON BR.RESOURCE_ID = WT.RESOURCE_ID
   AND BR.ORGANIZATION_ID = WT.ORGANIZATION_ID
LEFT JOIN APPS.FND_USER CREATED_USER
    ON CREATED_USER.USER_ID = WT.CREATED_BY
LEFT JOIN APPS.PER_ALL_PEOPLE_F CREATED_PERSON
    ON CREATED_PERSON.PERSON_ID = CREATED_USER.EMPLOYEE_ID
   AND SYSDATE BETWEEN CREATED_PERSON.EFFECTIVE_START_DATE AND CREATED_PERSON.EFFECTIVE_END_DATE
LEFT JOIN APPS.FND_USER UPDATED_USER
    ON UPDATED_USER.USER_ID = WT.LAST_UPDATED_BY
LEFT JOIN APPS.PER_ALL_PEOPLE_F UPDATED_PERSON
    ON UPDATED_PERSON.PERSON_ID = UPDATED_USER.EMPLOYEE_ID
   AND SYSDATE BETWEEN UPDATED_PERSON.EFFECTIVE_START_DATE AND UPDATED_PERSON.EFFECTIVE_END_DATE
WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
  AND EWO.ASSET_NUMBER = __ASSET_NUMBER__
  AND WT.TRANSACTION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
  AND BR.UNIT_OF_MEASURE = 'HR'
UNION ALL
SELECT
    'PENDING' AS TIME_SOURCE,
    EWO.WIP_ENTITY_NAME AS WORK_ORDER,
    EWO.WORK_ORDER_STATUS,
    EWO.ASSET_NUMBER,
    EWO.ASSET_DESCRIPTION,
    EWO.DESCRIPTION AS WO_DESCRIPTION,
    WCTI.TRANSACTION_ID,
    TO_CHAR(WCTI.TRANSACTION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS TRANSACTION_DATE,
    WCTI.OPERATION_SEQ_NUM,
    WCTI.RESOURCE_SEQ_NUM,
    BR.RESOURCE_CODE,
    BR.DESCRIPTION AS RESOURCE_DESCRIPTION,
    BR.UNIT_OF_MEASURE AS RESOURCE_UOM,
    WCTI.TRANSACTION_QUANTITY,
    WCTI.TRANSACTION_UOM,
    WCTI.PRIMARY_QUANTITY,
    WCTI.PRIMARY_UOM,
    CREATED_USER.USER_NAME AS CREATED_BY_USER,
    COALESCE(CREATED_PERSON.FULL_NAME, CREATED_USER.DESCRIPTION, CREATED_USER.USER_NAME) AS CREATED_BY_NAME,
    UPDATED_USER.USER_NAME AS LAST_UPDATED_BY_USER,
    COALESCE(UPDATED_PERSON.FULL_NAME, UPDATED_USER.DESCRIPTION, UPDATED_USER.USER_NAME) AS LAST_UPDATED_BY_NAME,
    WCTI.PROCESS_PHASE,
    CASE WCTI.PROCESS_PHASE
        WHEN 1 THEN 'Resource validation'
        WHEN 2 THEN 'Resource processing'
        WHEN 3 THEN 'Job close'
        WHEN 4 THEN 'Period close'
        ELSE NULL
    END AS PROCESS_PHASE_MEANING,
    WCTI.PROCESS_STATUS,
    CASE WCTI.PROCESS_STATUS
        WHEN 1 THEN 'Pending'
        WHEN 2 THEN 'Running'
        WHEN 3 THEN 'Error'
        WHEN 4 THEN 'Complete'
        WHEN 5 THEN 'Warning'
        ELSE NULL
    END AS PROCESS_STATUS_MEANING,
    CASE
        WHEN WCTI.TRANSACTION_QUANTITY >= 24 THEN 'Y'
        ELSE 'N'
    END AS IS_LARGE_TIME_TRANSACTION
FROM WIP.WIP_COST_TXN_INTERFACE WCTI
JOIN APPS.EAM_WORK_ORDERS_V EWO
    ON EWO.WIP_ENTITY_ID = WCTI.WIP_ENTITY_ID
   AND EWO.ORGANIZATION_ID = WCTI.ORGANIZATION_ID
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
LEFT JOIN BOM.BOM_RESOURCES BR
    ON BR.RESOURCE_ID = WCTI.RESOURCE_ID
   AND BR.ORGANIZATION_ID = WCTI.ORGANIZATION_ID
LEFT JOIN APPS.FND_USER CREATED_USER
    ON CREATED_USER.USER_ID = WCTI.CREATED_BY
LEFT JOIN APPS.PER_ALL_PEOPLE_F CREATED_PERSON
    ON CREATED_PERSON.PERSON_ID = CREATED_USER.EMPLOYEE_ID
   AND SYSDATE BETWEEN CREATED_PERSON.EFFECTIVE_START_DATE AND CREATED_PERSON.EFFECTIVE_END_DATE
LEFT JOIN APPS.FND_USER UPDATED_USER
    ON UPDATED_USER.USER_ID = WCTI.LAST_UPDATED_BY
LEFT JOIN APPS.PER_ALL_PEOPLE_F UPDATED_PERSON
    ON UPDATED_PERSON.PERSON_ID = UPDATED_USER.EMPLOYEE_ID
   AND SYSDATE BETWEEN UPDATED_PERSON.EFFECTIVE_START_DATE AND UPDATED_PERSON.EFFECTIVE_END_DATE
WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
  AND EWO.ASSET_NUMBER = __ASSET_NUMBER__
  AND WCTI.TRANSACTION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
  AND BR.UNIT_OF_MEASURE = 'HR'
ORDER BY
    TRANSACTION_DATE DESC,
    WORK_ORDER DESC,
    TIME_SOURCE,
    TRANSACTION_ID DESC;

SPOOL OFF
EXIT
