SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT *
FROM (
    SELECT
        'QA_RESULTS' AS SOURCE_TABLE,
        QR.WORK_ORDER_ID AS ENTITY_ID,
        QR.QA_LAST_UPDATE_DATE AS CHANGE_DATE
    FROM APPS.QA_RESULTS QR
    WHERE QR.QA_LAST_UPDATED_BY = __USER_ID__
    UNION ALL
    SELECT
        'WIP_ENTITIES',
        WE.WIP_ENTITY_ID,
        WE.LAST_UPDATE_DATE
    FROM APPS.WIP_ENTITIES WE
    WHERE WE.LAST_UPDATED_BY = __USER_ID__
    UNION ALL
    SELECT
        'WIP_OPERATIONS',
        WO.WIP_ENTITY_ID,
        WO.LAST_UPDATE_DATE
    FROM APPS.WIP_OPERATIONS WO
    WHERE WO.LAST_UPDATED_BY = __USER_ID__
)
ORDER BY CHANGE_DATE DESC;

SPOOL OFF
EXIT
