SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT *
FROM (
    SELECT
        'QA_RESULTS' AS SOURCE_TABLE,
        QR.WORK_ORDER_ID AS ENTITY_ID,
        NVL(QR.QA_LAST_UPDATE_DATE, QR.QA_CREATION_DATE) AS CHANGE_DATE,
        CASE
            WHEN QR.QA_CREATED_BY = __USER_ID__ THEN 'CREATED'
            WHEN QR.QA_LAST_UPDATED_BY = __USER_ID__ THEN 'UPDATED'
        END AS ACTION
    FROM APPS.QA_RESULTS QR
    WHERE __USER_ID__ IN (QR.QA_CREATED_BY, QR.QA_LAST_UPDATED_BY)
      AND NVL(QR.QA_LAST_UPDATE_DATE, QR.QA_CREATION_DATE) >= TO_DATE(__DATE_FROM__, 'YYYY-MM-DD')
    UNION ALL
    SELECT
        'WIP_ENTITIES',
        WE.WIP_ENTITY_ID,
        NVL(WE.LAST_UPDATE_DATE, WE.CREATION_DATE),
        CASE
            WHEN WE.CREATED_BY = __USER_ID__ THEN 'CREATED'
            WHEN WE.LAST_UPDATED_BY = __USER_ID__ THEN 'UPDATED'
        END
    FROM APPS.WIP_ENTITIES WE
    WHERE __USER_ID__ IN (WE.CREATED_BY, WE.LAST_UPDATED_BY)
      AND NVL(WE.LAST_UPDATE_DATE, WE.CREATION_DATE) >= TO_DATE(__DATE_FROM__, 'YYYY-MM-DD')
    UNION ALL
    SELECT
        'WIP_OPERATIONS',
        WO.WIP_ENTITY_ID,
        WO.LAST_UPDATE_DATE,
        'UPDATED'
    FROM APPS.WIP_OPERATIONS WO
    WHERE WO.LAST_UPDATED_BY = __USER_ID__
      AND WO.LAST_UPDATE_DATE >= TO_DATE(__DATE_FROM__, 'YYYY-MM-DD')
)
ORDER BY CHANGE_DATE DESC;

SPOOL OFF
EXIT
