/* ------------------------------------------------------------
   Cancelled Work Orders – Last 15 Days
   Org: 1169
   Status: Cancelled
   Output file passed as &1
------------------------------------------------------------ */

SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET DEFINE ON

-- SQLcl CSV formatting (preferred in SQLcl)
SET SQLFORMAT CSV

SPOOL &1

SELECT
    EWO.WIP_ENTITY_NAME,
    EWO.CREATION_DATE,
    QR.QA_CREATION_DATE,
    QR.WORK_ORDER_ID,
    EWO.WORK_ORDER_STATUS,
    QR.MAINTENANCE_OP_SEQ,
    EWO.ASSET_ACTIVITY,
    EWO.ASSET_GROUP_ID,
    EWO.ASSET_DESCRIPTION,
    EWO.CLASS_CODE,
    QR.COLLECTION_ID,
    QR.OCCURRENCE,
    QR.PLAN_ID,
    QR.STATUS,
    QR.CHARACTER1 AS "Lot Number",
    QR.CHARACTER2 AS "Location",
    QR.CHARACTER3 AS "Reason",
    QR.CHARACTER4 AS "Adjustment",
    QR.COMMENT1   AS "Description"
FROM APPS.QA_RESULTS QR
JOIN APPS.EAM_WORK_ORDERS_V EWO
  ON QR.ORGANIZATION_ID = EWO.ORGANIZATION_ID
 AND QR.WORK_ORDER_ID  = EWO.WIP_ENTITY_ID
WHERE
    QR.QA_CREATION_DATE > SYSDATE - 15
AND QR.ORGANIZATION_ID = 1169
AND EWO.WORK_ORDER_STATUS = 'Cancelled'
ORDER BY
    QR.QA_CREATION_DATE DESC,
    QR.QA_LAST_UPDATE_DATE DESC;

SPOOL OFF
EXIT
