SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH CLASS_ASSETS AS (
    SELECT
        EWO.ORGANIZATION_ID,
        EWO.CLASS_CODE,
        EWO.ASSET_NUMBER,
        MAX(EWO.ASSET_DESCRIPTION) AS ASSET_DESCRIPTION,
        EWO.ASSET_GROUP_ID,
        MAX(EWO.CREATION_DATE) AS LATEST_WO_CREATION_DATE
    FROM APPS.EAM_WORK_ORDERS_V EWO
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND EWO.CLASS_CODE = __CLASS_CODE__
      AND EWO.ASSET_NUMBER IS NOT NULL
      AND EWO.ASSET_GROUP_ID IS NOT NULL
    GROUP BY
        EWO.ORGANIZATION_ID,
        EWO.CLASS_CODE,
        EWO.ASSET_NUMBER,
        EWO.ASSET_GROUP_ID
),
LATEST_WO AS (
    SELECT
        CA.ORGANIZATION_ID,
        CA.ASSET_NUMBER,
        CA.ASSET_GROUP_ID,
        MAX(EWO.WIP_ENTITY_NAME) KEEP (
            DENSE_RANK LAST ORDER BY EWO.CREATION_DATE, EWO.WIP_ENTITY_ID
        ) AS LATEST_WORK_ORDER
    FROM CLASS_ASSETS CA
    JOIN APPS.EAM_WORK_ORDERS_V EWO
        ON EWO.ORGANIZATION_ID = CA.ORGANIZATION_ID
       AND EWO.CLASS_CODE = CA.CLASS_CODE
       AND EWO.ASSET_NUMBER = CA.ASSET_NUMBER
       AND EWO.ASSET_GROUP_ID = CA.ASSET_GROUP_ID
       AND EWO.CREATION_DATE = CA.LATEST_WO_CREATION_DATE
    GROUP BY
        CA.ORGANIZATION_ID,
        CA.ASSET_NUMBER,
        CA.ASSET_GROUP_ID
)
SELECT
    CA.CLASS_CODE,
    CA.ASSET_NUMBER,
    CA.ASSET_DESCRIPTION,
    AG.SEGMENT1 AS ASSET_GROUP_ITEM,
    AG.DESCRIPTION AS ASSET_GROUP_DESCRIPTION,
    BBOM.BILL_SEQUENCE_ID,
    BBOM.COMMON_BILL_SEQUENCE_ID,
    BBOM.ALTERNATE_BOM_DESIGNATOR,
    BBOM.ASSEMBLY_TYPE,
    BIC.ITEM_NUM,
    BIC.COMPONENT_SEQUENCE_ID,
    COMP.SEGMENT1 AS PART_NUMBER,
    COMP.DESCRIPTION AS PART_DESCRIPTION,
    BIC.COMPONENT_QUANTITY,
    COMP.PRIMARY_UOM_CODE AS COMPONENT_UOM,
    BIC.COMPONENT_YIELD_FACTOR,
    BIC.COMPONENT_REMARKS,
    TO_CHAR(BIC.EFFECTIVITY_DATE, 'MM/DD/YYYY') AS EFFECTIVITY_DATE,
    TO_CHAR(BIC.DISABLE_DATE, 'MM/DD/YYYY') AS DISABLE_DATE,
    CASE
        WHEN BIC.EFFECTIVITY_DATE <= SYSDATE
         AND (BIC.DISABLE_DATE IS NULL OR BIC.DISABLE_DATE > SYSDATE)
        THEN 'Y'
        ELSE 'N'
    END AS CURRENTLY_ACTIVE,
    LWO.LATEST_WORK_ORDER,
    TO_CHAR(CA.LATEST_WO_CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS LATEST_WO_CREATION_DATE
FROM CLASS_ASSETS CA
LEFT JOIN LATEST_WO LWO
    ON LWO.ORGANIZATION_ID = CA.ORGANIZATION_ID
   AND LWO.ASSET_NUMBER = CA.ASSET_NUMBER
   AND LWO.ASSET_GROUP_ID = CA.ASSET_GROUP_ID
JOIN APPS.BOM_BILL_OF_MATERIALS BBOM
    ON BBOM.ASSEMBLY_ITEM_ID = CA.ASSET_GROUP_ID
   AND BBOM.ORGANIZATION_ID = CA.ORGANIZATION_ID
JOIN APPS.BOM_INVENTORY_COMPONENTS BIC
    ON BIC.BILL_SEQUENCE_ID = BBOM.COMMON_BILL_SEQUENCE_ID
LEFT JOIN INV.MTL_SYSTEM_ITEMS_B AG
    ON AG.INVENTORY_ITEM_ID = CA.ASSET_GROUP_ID
   AND AG.ORGANIZATION_ID = CA.ORGANIZATION_ID
LEFT JOIN INV.MTL_SYSTEM_ITEMS_B COMP
    ON COMP.INVENTORY_ITEM_ID = BIC.COMPONENT_ITEM_ID
   AND COMP.ORGANIZATION_ID = CA.ORGANIZATION_ID
WHERE __ACTIVE_ONLY__ = 0
   OR (
        BIC.EFFECTIVITY_DATE <= SYSDATE
        AND (BIC.DISABLE_DATE IS NULL OR BIC.DISABLE_DATE > SYSDATE)
      )
ORDER BY
    CA.CLASS_CODE,
    CA.ASSET_NUMBER,
    BBOM.ALTERNATE_BOM_DESIGNATOR,
    BIC.ITEM_NUM,
    COMP.SEGMENT1;

SPOOL OFF
EXIT
