SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH DEPT_ASSETS AS (
    SELECT DISTINCT
        EWO.ORGANIZATION_ID,
        WO.DEPARTMENT_CODE,
        WO.OPERATION_SEQ_NUM AS MATCHED_OPERATION_SEQ,
        EWO.ASSET_NUMBER,
        EWO.ASSET_DESCRIPTION,
        EWO.ASSET_GROUP_ID
    FROM APPS.WIP_OPERATIONS_V WO
    JOIN APPS.EAM_WORK_ORDERS_V EWO
        ON EWO.WIP_ENTITY_ID = WO.WIP_ENTITY_ID
       AND EWO.ORGANIZATION_ID = WO.ORGANIZATION_ID
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND WO.DEPARTMENT_CODE = __DEPARTMENT_CODE__
      AND (__OPERATION_SEQ__ = 0 OR WO.OPERATION_SEQ_NUM = __OPERATION_SEQ__)
      AND EWO.WIP_ENTITY_NAME LIKE 'PM%'
      AND EWO.WORK_ORDER_STATUS = 'Released'
      AND EWO.ASSET_NUMBER IS NOT NULL
      AND EWO.ASSET_GROUP_ID IS NOT NULL
)
SELECT
    DA.DEPARTMENT_CODE,
    DA.MATCHED_OPERATION_SEQ,
    DA.ASSET_NUMBER,
    DA.ASSET_DESCRIPTION,
    AG.SEGMENT1 AS ASSET_GROUP_ITEM,
    AG.DESCRIPTION AS ASSET_GROUP_DESCRIPTION,
    BBOM.BILL_SEQUENCE_ID,
    BBOM.COMMON_BILL_SEQUENCE_ID,
    BBOM.ALTERNATE_BOM_DESIGNATOR,
    BBOM.ASSEMBLY_TYPE,
    BIC.ITEM_NUM,
    BIC.COMPONENT_SEQUENCE_ID,
    COMP.SEGMENT1 AS PART_NUMBER,
    COMP.DESCRIPTION AS PART_DESCRIPTION,
    BIC.COMPONENT_QUANTITY,
    COMP.PRIMARY_UOM_CODE AS COMPONENT_UOM,
    BIC.COMPONENT_YIELD_FACTOR,
    BIC.COMPONENT_REMARKS,
    TO_CHAR(BIC.EFFECTIVITY_DATE, 'MM/DD/YYYY') AS EFFECTIVITY_DATE,
    TO_CHAR(BIC.DISABLE_DATE, 'MM/DD/YYYY') AS DISABLE_DATE,
    CASE
        WHEN BIC.EFFECTIVITY_DATE <= SYSDATE
         AND (BIC.DISABLE_DATE IS NULL OR BIC.DISABLE_DATE > SYSDATE)
        THEN 'Y'
        ELSE 'N'
    END AS CURRENTLY_ACTIVE
FROM DEPT_ASSETS DA
JOIN APPS.BOM_BILL_OF_MATERIALS BBOM
    ON BBOM.ASSEMBLY_ITEM_ID = DA.ASSET_GROUP_ID
   AND BBOM.ORGANIZATION_ID = DA.ORGANIZATION_ID
JOIN APPS.BOM_INVENTORY_COMPONENTS BIC
    ON BIC.BILL_SEQUENCE_ID = BBOM.COMMON_BILL_SEQUENCE_ID
LEFT JOIN INV.MTL_SYSTEM_ITEMS_B AG
    ON AG.INVENTORY_ITEM_ID = DA.ASSET_GROUP_ID
   AND AG.ORGANIZATION_ID = DA.ORGANIZATION_ID
LEFT JOIN INV.MTL_SYSTEM_ITEMS_B COMP
    ON COMP.INVENTORY_ITEM_ID = BIC.COMPONENT_ITEM_ID
   AND COMP.ORGANIZATION_ID = DA.ORGANIZATION_ID
WHERE __ACTIVE_ONLY__ = 0
   OR (
        BIC.EFFECTIVITY_DATE <= SYSDATE
        AND (BIC.DISABLE_DATE IS NULL OR BIC.DISABLE_DATE > SYSDATE)
      )
ORDER BY
    DA.DEPARTMENT_CODE,
    DA.ASSET_NUMBER,
    BBOM.ALTERNATE_BOM_DESIGNATOR,
    BIC.ITEM_NUM,
    COMP.SEGMENT1;

SPOOL OFF
EXIT
