SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    BR.RESOURCE_CODE,
    BR.DESCRIPTION AS RESOURCE_DESCRIPTION,
    BR.RESOURCE_TYPE,
    PEO.FULL_NAME,
    FU.USER_NAME AS BADGE_NUMBER,
    FU.EMAIL_ADDRESS,
    BRE.EFFECTIVE_START_DATE,
    BRE.EFFECTIVE_END_DATE
FROM BOM.BOM_RESOURCES BR
JOIN BOM.BOM_RESOURCE_EMPLOYEES BRE
    ON BRE.RESOURCE_ID = BR.RESOURCE_ID
   AND BRE.ORGANIZATION_ID = BR.ORGANIZATION_ID
JOIN APPS.PER_ALL_PEOPLE_F PEO
    ON PEO.PERSON_ID = BRE.PERSON_ID
   AND SYSDATE BETWEEN PEO.EFFECTIVE_START_DATE AND PEO.EFFECTIVE_END_DATE
LEFT JOIN APPS.FND_USER FU
    ON FU.EMPLOYEE_ID = PEO.PERSON_ID
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = BR.ORGANIZATION_ID
WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
  AND BR.RESOURCE_CODE = __RESOURCE_CODE__
  AND SYSDATE <= BRE.EFFECTIVE_END_DATE
ORDER BY PEO.FULL_NAME;

SPOOL OFF
EXIT
