SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH EQUIPMENT_WOS AS (
    SELECT
        EWO.ORGANIZATION_ID,
        EWO.WIP_ENTITY_ID,
        EWO.WIP_ENTITY_NAME AS WORK_ORDER,
        CASE
            WHEN EWO.WIP_ENTITY_NAME LIKE 'PM%'
              OR UPPER(NVL(EWO.WORK_ORDER_TYPE_DISP, '')) IN ('PM', 'PREVENTIVE MAINTENANCE')
            THEN 'PLANNED'
            ELSE 'REACTIVE'
        END AS MAINTENANCE_SPLIT,
        EWO.WORK_ORDER_STATUS,
        EWO.WORK_ORDER_TYPE_DISP AS WO_TYPE,
        EWO.CLASS_CODE,
        EWO.ASSET_NUMBER,
        EWO.ASSET_DESCRIPTION,
        EWO.ASSET_ACTIVITY,
        EWO.DESCRIPTION AS WORK_ORDER_DESCRIPTION,
        EWO.CREATION_DATE AS WO_CREATED_DATE,
        EWO.SCHEDULED_START_DATE
    FROM APPS.EAM_WORK_ORDERS_V EWO
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND EWO.ASSET_NUMBER IS NOT NULL
      AND EWO.CREATION_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -__MONTHS__)
      AND (__ASSET_NUMBER__ = 'ALL' OR EWO.ASSET_NUMBER = __ASSET_NUMBER__)
),
OP10_DEPT AS (
    SELECT
        WO.ORGANIZATION_ID,
        WO.WIP_ENTITY_ID,
        BD.DEPARTMENT_CODE AS PRIMARY_DEPARTMENT_CODE,
        BD.DESCRIPTION AS PRIMARY_DEPARTMENT_DESCRIPTION
    FROM APPS.WIP_OPERATIONS_V WO
    LEFT JOIN BOM.BOM_DEPARTMENTS BD
        ON BD.DEPARTMENT_ID = WO.DEPARTMENT_ID
       AND BD.ORGANIZATION_ID = WO.ORGANIZATION_ID
    WHERE WO.OPERATION_SEQ_NUM = 10
),
DIRECT_PO AS (
    SELECT
        'DIRECT_PO_DISTRIBUTION_WIP_ENTITY_ID' AS SOURCE_PATH,
        EW.ORGANIZATION_ID,
        EW.WIP_ENTITY_ID,
        EW.WORK_ORDER,
        EW.MAINTENANCE_SPLIT,
        EW.WORK_ORDER_STATUS,
        EW.WO_TYPE,
        EW.CLASS_CODE,
        EW.ASSET_NUMBER,
        EW.ASSET_DESCRIPTION,
        EW.ASSET_ACTIVITY,
        EW.WORK_ORDER_DESCRIPTION,
        EW.WO_CREATED_DATE,
        EW.SCHEDULED_START_DATE,
        POH.PO_HEADER_ID,
        POH.SEGMENT1 AS PO_NUMBER,
        POH.AUTHORIZATION_STATUS AS PO_STATUS,
        POH.CREATION_DATE AS PO_CREATED_DATE,
        POH.APPROVED_DATE AS PO_APPROVED_DATE,
        APS.VENDOR_NAME AS SUPPLIER_NAME,
        POL.PO_LINE_ID,
        POL.LINE_NUM AS PO_LINE_NUM,
        POL.ITEM_ID,
        COALESCE(MSI.SEGMENT1, TO_CHAR(POL.ITEM_ID)) AS ITEM_NUMBER,
        COALESCE(MSI.DESCRIPTION, POL.ITEM_DESCRIPTION) AS PO_LINE_DESCRIPTION,
        POL.UNIT_MEAS_LOOKUP_CODE AS PO_UOM,
        POL.UNIT_PRICE,
        POD.QUANTITY_ORDERED,
        POD.QUANTITY_DELIVERED,
        POD.QUANTITY_BILLED,
        POD.AMOUNT_ORDERED,
        POD.AMOUNT_DELIVERED,
        POD.AMOUNT_BILLED,
        POD.PO_DISTRIBUTION_ID,
        CAST(NULL AS VARCHAR2(80)) AS REQUISITION_NUMBER,
        CAST(NULL AS NUMBER) AS REQUISITION_LINE_NUM
    FROM EQUIPMENT_WOS EW
    JOIN PO.PO_DISTRIBUTIONS_ALL POD
        ON POD.WIP_ENTITY_ID = EW.WIP_ENTITY_ID
       AND POD.DESTINATION_ORGANIZATION_ID = EW.ORGANIZATION_ID
    JOIN PO.PO_HEADERS_ALL POH
        ON POH.PO_HEADER_ID = POD.PO_HEADER_ID
    JOIN PO.PO_LINES_ALL POL
        ON POL.PO_LINE_ID = POD.PO_LINE_ID
    LEFT JOIN INV.MTL_SYSTEM_ITEMS_B MSI
        ON MSI.INVENTORY_ITEM_ID = POL.ITEM_ID
       AND MSI.ORGANIZATION_ID = EW.ORGANIZATION_ID
    LEFT JOIN APPS.AP_SUPPLIERS APS
        ON APS.VENDOR_ID = POH.VENDOR_ID
    WHERE POH.CREATION_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -__MONTHS__)
),
REQ_PO AS (
    SELECT
        'REQUISITION_LINE_WIP_ENTITY_ID' AS SOURCE_PATH,
        EW.ORGANIZATION_ID,
        EW.WIP_ENTITY_ID,
        EW.WORK_ORDER,
        EW.MAINTENANCE_SPLIT,
        EW.WORK_ORDER_STATUS,
        EW.WO_TYPE,
        EW.CLASS_CODE,
        EW.ASSET_NUMBER,
        EW.ASSET_DESCRIPTION,
        EW.ASSET_ACTIVITY,
        EW.WORK_ORDER_DESCRIPTION,
        EW.WO_CREATED_DATE,
        EW.SCHEDULED_START_DATE,
        POH.PO_HEADER_ID,
        POH.SEGMENT1 AS PO_NUMBER,
        POH.AUTHORIZATION_STATUS AS PO_STATUS,
        POH.CREATION_DATE AS PO_CREATED_DATE,
        POH.APPROVED_DATE AS PO_APPROVED_DATE,
        APS.VENDOR_NAME AS SUPPLIER_NAME,
        POL.PO_LINE_ID,
        POL.LINE_NUM AS PO_LINE_NUM,
        POL.ITEM_ID,
        COALESCE(MSI.SEGMENT1, TO_CHAR(POL.ITEM_ID)) AS ITEM_NUMBER,
        COALESCE(MSI.DESCRIPTION, POL.ITEM_DESCRIPTION, PRL.ITEM_DESCRIPTION) AS PO_LINE_DESCRIPTION,
        POL.UNIT_MEAS_LOOKUP_CODE AS PO_UOM,
        POL.UNIT_PRICE,
        POD.QUANTITY_ORDERED,
        POD.QUANTITY_DELIVERED,
        POD.QUANTITY_BILLED,
        POD.AMOUNT_ORDERED,
        POD.AMOUNT_DELIVERED,
        POD.AMOUNT_BILLED,
        POD.PO_DISTRIBUTION_ID,
        PRH.SEGMENT1 AS REQUISITION_NUMBER,
        PRL.LINE_NUM AS REQUISITION_LINE_NUM
    FROM EQUIPMENT_WOS EW
    JOIN PO.PO_REQUISITION_LINES_ALL PRL
        ON PRL.WIP_ENTITY_ID = EW.WIP_ENTITY_ID
       AND PRL.DESTINATION_ORGANIZATION_ID = EW.ORGANIZATION_ID
    JOIN PO.PO_REQUISITION_HEADERS_ALL PRH
        ON PRH.REQUISITION_HEADER_ID = PRL.REQUISITION_HEADER_ID
    JOIN PO.PO_REQ_DISTRIBUTIONS_ALL PRD
        ON PRD.REQUISITION_LINE_ID = PRL.REQUISITION_LINE_ID
    JOIN PO.PO_DISTRIBUTIONS_ALL POD
        ON POD.REQ_DISTRIBUTION_ID = PRD.DISTRIBUTION_ID
    JOIN PO.PO_HEADERS_ALL POH
        ON POH.PO_HEADER_ID = POD.PO_HEADER_ID
    JOIN PO.PO_LINES_ALL POL
        ON POL.PO_LINE_ID = POD.PO_LINE_ID
    LEFT JOIN INV.MTL_SYSTEM_ITEMS_B MSI
        ON MSI.INVENTORY_ITEM_ID = POL.ITEM_ID
       AND MSI.ORGANIZATION_ID = EW.ORGANIZATION_ID
    LEFT JOIN APPS.AP_SUPPLIERS APS
        ON APS.VENDOR_ID = POH.VENDOR_ID
    WHERE POH.CREATION_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -__MONTHS__)
),
ALL_PO AS (
    SELECT * FROM DIRECT_PO
    UNION ALL
    SELECT * FROM REQ_PO
)
SELECT
    AP.SOURCE_PATH,
    AP.PO_NUMBER,
    AP.PO_STATUS,
    TO_CHAR(AP.PO_CREATED_DATE, 'MM/DD/YYYY') AS PO_CREATED_DATE,
    TO_CHAR(AP.PO_APPROVED_DATE, 'MM/DD/YYYY') AS PO_APPROVED_DATE,
    AP.SUPPLIER_NAME,
    AP.PO_LINE_NUM,
    AP.ITEM_NUMBER,
    AP.PO_LINE_DESCRIPTION,
    AP.PO_UOM,
    AP.UNIT_PRICE,
    AP.QUANTITY_ORDERED,
    AP.QUANTITY_DELIVERED,
    AP.QUANTITY_BILLED,
    AP.AMOUNT_ORDERED,
    AP.AMOUNT_DELIVERED,
    AP.AMOUNT_BILLED,
    AP.REQUISITION_NUMBER,
    AP.REQUISITION_LINE_NUM,
    AP.WORK_ORDER,
    AP.MAINTENANCE_SPLIT,
    AP.WORK_ORDER_STATUS,
    AP.WO_TYPE,
    AP.CLASS_CODE,
    TO_CHAR(AP.WO_CREATED_DATE, 'MM/DD/YYYY') AS WO_CREATED_DATE,
    TO_CHAR(AP.SCHEDULED_START_DATE, 'MM/DD/YYYY') AS SCHEDULED_START_DATE,
    AP.ASSET_NUMBER,
    AP.ASSET_DESCRIPTION,
    AP.ASSET_ACTIVITY,
    AP.WORK_ORDER_DESCRIPTION,
    OP10.PRIMARY_DEPARTMENT_CODE,
    OP10.PRIMARY_DEPARTMENT_DESCRIPTION,
    AP.PO_DISTRIBUTION_ID,
    AP.PO_HEADER_ID,
    AP.PO_LINE_ID,
    AP.WIP_ENTITY_ID
FROM ALL_PO AP
LEFT JOIN OP10_DEPT OP10
    ON OP10.ORGANIZATION_ID = AP.ORGANIZATION_ID
   AND OP10.WIP_ENTITY_ID = AP.WIP_ENTITY_ID
WHERE (__DEPARTMENT_CODE__ = 'ALL' OR OP10.PRIMARY_DEPARTMENT_CODE = __DEPARTMENT_CODE__)
  AND (
        __SPLIT__ = 'ALL'
        OR (__SPLIT__ = 'PLANNED' AND AP.MAINTENANCE_SPLIT = 'PLANNED')
        OR (__SPLIT__ = 'REACTIVE' AND AP.MAINTENANCE_SPLIT = 'REACTIVE')
      )
ORDER BY
    AP.PO_CREATED_DATE DESC,
    AP.PO_NUMBER,
    AP.PO_LINE_NUM,
    AP.WORK_ORDER,
    AP.PO_DISTRIBUTION_ID;

SPOOL OFF
EXIT
