-- level10_dm_open.sql
-- Level 10 DM Open Work Orders
-- Output file passed as &1

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT 1

SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET DEFINE ON
SET SQLFORMAT CSV

SPOOL &1

SELECT DISTINCT
    EWO.WIP_ENTITY_NAME,
    EWO.WIP_ENTITY_ID,
    TO_CHAR(EWO.CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS CREATION_DATE_TIME,
    EWO.ASSET_NUMBER,
    EWO.WORK_ORDER_STATUS,
    WO2.OPERATION_SEQ_NUM,
    WO2.OPERATION_COMPLETED,
    RES.INSTANCE_NAME,
    EWO.DESCRIPTION
FROM
    APPS.WIP_OPERATIONS_V WO1
JOIN APPS.EAM_WORK_ORDERS_V EWO
    ON EWO.WIP_ENTITY_ID = WO1.WIP_ENTITY_ID
JOIN APPS.WIP_OPERATIONS_V WO2
    ON EWO.WIP_ENTITY_ID = WO2.WIP_ENTITY_ID
JOIN APPS.WIP_OP_RESOURCE_INSTANCES_V RES
    ON RES.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
   AND RES.OPERATION_SEQ_NUM = WO2.OPERATION_SEQ_NUM
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
WHERE
    EWO.ORGANIZATION_ID = 1169
    AND WO1.OPERATION_SEQ_NUM = 10
    AND WO2.OPERATION_SEQ_NUM = 10
    AND WO1.OPERATION_COMPLETED = 'N'
    AND EWO.USER_DEFINED_STATUS_ID = 3
    AND MP.ORGANIZATION_CODE = 'XAU'
    AND EWO.WORK_ORDER_TYPE_DISP = 'DM'
    AND EWO.ASSET_NUMBER LIKE 'AU%'
ORDER BY
    CREATION_DATE_TIME ASC;

SPOOL OFF
EXIT
