SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    USER_ID,
    USER_NAME,
    DESCRIPTION AS FULL_NAME,
    EMAIL_ADDRESS,
    EMPLOYEE_ID,
    END_DATE
FROM APPS.FND_USER
WHERE USER_NAME = __IDENTIFIER__
   OR TO_CHAR(USER_ID) = __IDENTIFIER__
   OR TO_CHAR(EMPLOYEE_ID) = __IDENTIFIER__;

SPOOL OFF
EXIT
