SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    MP.ORGANIZATION_CODE,
    WO.DEPARTMENT_CODE,
    EWO.ASSET_NUMBER,
    EWO.ASSET_DESCRIPTION,
    EWO.ASSET_GROUP_ID,
    AG.SEGMENT1 AS ASSET_GROUP_ITEM,
    AG.DESCRIPTION AS ASSET_GROUP_DESCRIPTION,
    COUNT(DISTINCT EWO.WIP_ENTITY_ID) AS WORK_ORDER_COUNT_ALL_TIME,
    SUM(CASE WHEN EWO.CREATION_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -12) THEN 1 ELSE 0 END)
        AS WORK_ORDER_COUNT_12MO,
    MIN(EWO.CREATION_DATE) AS FIRST_WORK_ORDER_DATE,
    MAX(EWO.CREATION_DATE) AS LAST_WORK_ORDER_DATE
FROM APPS.EAM_WORK_ORDERS_V EWO
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
LEFT JOIN APPS.WIP_OPERATIONS_V WO
    ON WO.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
   AND WO.ORGANIZATION_ID = EWO.ORGANIZATION_ID
LEFT JOIN INV.MTL_SYSTEM_ITEMS_B AG
    ON AG.INVENTORY_ITEM_ID = EWO.ASSET_GROUP_ID
   AND AG.ORGANIZATION_ID = EWO.ORGANIZATION_ID
WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
  AND EWO.ASSET_NUMBER IS NOT NULL
  AND EWO.ASSET_DESCRIPTION IS NOT NULL
GROUP BY
    MP.ORGANIZATION_CODE,
    WO.DEPARTMENT_CODE,
    EWO.ASSET_NUMBER,
    EWO.ASSET_DESCRIPTION,
    EWO.ASSET_GROUP_ID,
    AG.SEGMENT1,
    AG.DESCRIPTION
ORDER BY
    WO.DEPARTMENT_CODE,
    AG.DESCRIPTION,
    EWO.ASSET_NUMBER;

SPOOL OFF
EXIT
