SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    EWO.ASSET_NUMBER,
    EWO.ASSET_DESCRIPTION,
    MSI.SEGMENT1 AS PART_NUMBER,
    MSI.DESCRIPTION AS PART_DESCRIPTION,
    COUNT(MMT.TRANSACTION_ID) AS TIMES_ISSUED,
    SUM(ABS(MMT.TRANSACTION_QUANTITY)) AS TOTAL_QTY_CONSUMED,
    SUM(ABS(MMT.TRANSACTION_QUANTITY) * NVL(MMT.TRANSACTION_COST, MMT.ACTUAL_COST)) AS TOTAL_MATERIAL_COST,
    MMT.TRANSACTION_UOM AS UOM
FROM APPS.EAM_WORK_ORDERS_V EWO
JOIN INV.MTL_MATERIAL_TRANSACTIONS MMT
    ON MMT.TRANSACTION_SOURCE_ID = EWO.WIP_ENTITY_ID
   AND MMT.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND MMT.TRANSACTION_SOURCE_TYPE_ID = 5
   AND MMT.TRANSACTION_QUANTITY < 0
JOIN INV.MTL_SYSTEM_ITEMS_B MSI
    ON MSI.INVENTORY_ITEM_ID = MMT.INVENTORY_ITEM_ID
   AND MSI.ORGANIZATION_ID = MMT.ORGANIZATION_ID
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
  AND EWO.ASSET_NUMBER = __ASSET_NUMBER__
  AND MMT.TRANSACTION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
GROUP BY EWO.ASSET_NUMBER, EWO.ASSET_DESCRIPTION, MSI.SEGMENT1, MSI.DESCRIPTION, MMT.TRANSACTION_UOM
ORDER BY TOTAL_MATERIAL_COST DESC, TOTAL_QTY_CONSUMED DESC;

SPOOL OFF
EXIT
