SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT DISTINCT
    PEO.FULL_NAME,
    FU.USER_NAME AS BADGE_NUMBER,
    EWO.WIP_ENTITY_NAME AS WORK_ORDER,
    EWO.WORK_ORDER_STATUS,
    EWO.ASSET_NUMBER,
    EWO.ASSET_ACTIVITY,
    EWO.ASSET_DESCRIPTION,
    TO_CHAR(QR.QA_CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS INSPECTION_DATE,
    QR.CHARACTER1 AS LOT_NUMBER,
    QR.CHARACTER2 AS LOCATION,
    QR.CHARACTER3 AS REASON,
    QR.CHARACTER4 AS ADJUSTMENT,
    QR.COMMENT1 AS DESCRIPTION
FROM APPS.PER_ALL_PEOPLE_F PEO
JOIN APPS.FND_USER FU
    ON FU.EMPLOYEE_ID = PEO.PERSON_ID
JOIN APPS.QA_RESULTS QR
    ON QR.QA_CREATED_BY = FU.USER_ID
JOIN APPS.EAM_WORK_ORDERS_V EWO
    ON EWO.WIP_ENTITY_ID = QR.WORK_ORDER_ID
   AND EWO.ORGANIZATION_ID = QR.ORGANIZATION_ID
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = QR.ORGANIZATION_ID
WHERE SYSDATE BETWEEN PEO.EFFECTIVE_START_DATE AND PEO.EFFECTIVE_END_DATE
  AND MP.ORGANIZATION_CODE = __ORG_CODE__
  AND UPPER(PEO.FULL_NAME) LIKE UPPER('%' || __NAME__ || '%')
  AND QR.QA_CREATION_DATE >= SYSDATE - __DAYS__
ORDER BY QR.QA_CREATION_DATE DESC;

SPOOL OFF
EXIT
