SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH PERSON_MATCH AS (
    SELECT
        FU.USER_ID,
        FU.USER_NAME AS BADGE_NUMBER,
        PEO.FULL_NAME
    FROM APPS.PER_ALL_PEOPLE_F PEO
    JOIN APPS.FND_USER FU
        ON FU.EMPLOYEE_ID = PEO.PERSON_ID
    WHERE SYSDATE BETWEEN PEO.EFFECTIVE_START_DATE AND PEO.EFFECTIVE_END_DATE
      AND (
            UPPER(PEO.FULL_NAME) LIKE UPPER('%' || __NAME__ || '%')
         OR UPPER(FU.DESCRIPTION) LIKE UPPER('%' || __NAME__ || '%')
         OR UPPER(FU.USER_NAME) LIKE UPPER('%' || __NAME__ || '%')
      )
),
TOUCHED_WO AS (
    SELECT DISTINCT
        PM.FULL_NAME,
        PM.BADGE_NUMBER,
        EWO.ORGANIZATION_ID,
        EWO.WIP_ENTITY_ID,
        EWO.WIP_ENTITY_NAME AS WORK_ORDER,
        EWO.WORK_ORDER_STATUS,
        EWO.ASSET_NUMBER,
        EWO.ASSET_DESCRIPTION,
        MAX(QR.QA_CREATION_DATE) OVER (
            PARTITION BY EWO.ORGANIZATION_ID, EWO.WIP_ENTITY_ID
        ) AS LAST_TOUCH_DATE
    FROM PERSON_MATCH PM
    JOIN APPS.QA_RESULTS QR
        ON QR.QA_CREATED_BY = PM.USER_ID
    JOIN APPS.EAM_WORK_ORDERS_V EWO
        ON EWO.WIP_ENTITY_ID = QR.WORK_ORDER_ID
       AND EWO.ORGANIZATION_ID = QR.ORGANIZATION_ID
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = QR.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND QR.QA_CREATION_DATE >= SYSDATE - __DAYS__
)
SELECT
    TWO.FULL_NAME,
    TWO.BADGE_NUMBER,
    TWO.WORK_ORDER,
    TWO.WORK_ORDER_STATUS,
    TWO.ASSET_NUMBER,
    TWO.ASSET_DESCRIPTION,
    TO_CHAR(TWO.LAST_TOUCH_DATE, 'MM/DD/YYYY HH24:MI:SS') AS LAST_TOUCH_DATE,
    MTT.TRANSACTION_TYPE_NAME AS TRANSACTION_TYPE,
    TO_CHAR(MMT.TRANSACTION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS TRANSACTION_DATE,
    MSI.SEGMENT1 AS PART_NUMBER,
    MSI.DESCRIPTION AS PART_DESCRIPTION,
    MMT.TRANSACTION_QUANTITY AS QTY,
    NVL(MMT.TRANSACTION_COST, MMT.ACTUAL_COST) AS UNIT_MATERIAL_COST,
    ABS(MMT.TRANSACTION_QUANTITY) * NVL(MMT.TRANSACTION_COST, MMT.ACTUAL_COST) AS LINE_MATERIAL_COST,
    MMT.TRANSACTION_UOM AS UOM,
    MMT.SUBINVENTORY_CODE AS FROM_SUBINVENTORY,
    MMT.TRANSACTION_REFERENCE AS REFERENCE
FROM TOUCHED_WO TWO
JOIN INV.MTL_MATERIAL_TRANSACTIONS MMT
    ON MMT.TRANSACTION_SOURCE_ID = TWO.WIP_ENTITY_ID
   AND MMT.ORGANIZATION_ID = TWO.ORGANIZATION_ID
   AND MMT.TRANSACTION_SOURCE_TYPE_ID = 5
   AND MMT.TRANSACTION_QUANTITY < 0
JOIN INV.MTL_SYSTEM_ITEMS_B MSI
    ON MSI.INVENTORY_ITEM_ID = MMT.INVENTORY_ITEM_ID
   AND MSI.ORGANIZATION_ID = MMT.ORGANIZATION_ID
LEFT JOIN INV.MTL_TRANSACTION_TYPES MTT
    ON MTT.TRANSACTION_TYPE_ID = MMT.TRANSACTION_TYPE_ID
ORDER BY
    TWO.LAST_TOUCH_DATE DESC,
    TWO.WORK_ORDER,
    MMT.TRANSACTION_DATE DESC,
    MSI.SEGMENT1;

SPOOL OFF
EXIT
