SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH PM_RESOURCE_LINES AS (
    SELECT
        TRUNC(EWO.CREATION_DATE, 'MM') AS PM_MONTH_DATE,
        EWO.WIP_ENTITY_ID,
        EWO.WIP_ENTITY_NAME AS WORK_ORDER,
        BR.RESOURCE_CODE,
        BR.DESCRIPTION AS RESOURCE_DESCRIPTION,
        NVL(WOR.USAGE_RATE_OR_AMOUNT, 0) AS DOCUMENTED_PM_HOURS,
        CASE
            WHEN UPPER(BR.RESOURCE_CODE) LIKE 'EL%'
              OR UPPER(BR.RESOURCE_CODE) LIKE 'EE%'
              OR UPPER(BR.DESCRIPTION) LIKE '%ELECT%'
            THEN 'ELECTRICAL'
            WHEN UPPER(BR.RESOURCE_CODE) IN ('M1025', 'MBU12')
              OR UPPER(BR.DESCRIPTION) LIKE '%CALIB%'
              OR UPPER(BR.DESCRIPTION) LIKE '%CONTROL%'
              OR UPPER(BR.DESCRIPTION) LIKE '%PLC%'
              OR UPPER(BR.DESCRIPTION) LIKE '%INSTRUMENT%'
              OR UPPER(BR.DESCRIPTION) LIKE '%SOFTWARE%'
              OR UPPER(BR.DESCRIPTION) LIKE '%VALIDATION%'
            THEN 'CONTROLS'
            WHEN UPPER(BR.RESOURCE_CODE) LIKE 'MM%'
              OR UPPER(BR.RESOURCE_CODE) IN ('MTU02', 'MTU90', 'KAU93', 'MAINTSUPV', 'PDM', 'PB016')
              OR UPPER(BR.DESCRIPTION) LIKE '%MAINTENANCE%'
              OR UPPER(BR.DESCRIPTION) LIKE '%HVAC%'
              OR UPPER(BR.DESCRIPTION) LIKE '%UTILIT%'
              OR UPPER(BR.DESCRIPTION) LIKE '%FACILIT%'
              OR UPPER(BR.DESCRIPTION) LIKE '%MACHINE SHOP%'
            THEN 'MECHANICAL'
            ELSE 'UNMAPPED'
        END AS CRAFT
    FROM WIP.WIP_OPERATION_RESOURCES WOR
    JOIN APPS.EAM_WORK_ORDERS_V EWO
        ON EWO.WIP_ENTITY_ID = WOR.WIP_ENTITY_ID
       AND EWO.ORGANIZATION_ID = WOR.ORGANIZATION_ID
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    JOIN BOM.BOM_RESOURCES BR
        ON BR.RESOURCE_ID = WOR.RESOURCE_ID
       AND BR.ORGANIZATION_ID = WOR.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND EWO.CREATION_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -__MONTHS__)
      AND (EWO.WIP_ENTITY_NAME LIKE 'PM%' OR UPPER(NVL(EWO.WORK_ORDER_TYPE_DISP, '')) IN ('PM', 'PREVENTIVE MAINTENANCE'))
      AND BR.UNIT_OF_MEASURE = 'HR'
),
MONTHS AS (
    SELECT ADD_MONTHS(TRUNC(ADD_MONTHS(SYSDATE, -__MONTHS__), 'MM'), LEVEL - 1) AS PM_MONTH_DATE
    FROM DUAL
    CONNECT BY ADD_MONTHS(TRUNC(ADD_MONTHS(SYSDATE, -__MONTHS__), 'MM'), LEVEL - 1) <= TRUNC(SYSDATE, 'MM')
),
CRAFTS AS (
    SELECT 'MECHANICAL' AS CRAFT FROM DUAL
    UNION ALL SELECT 'ELECTRICAL' FROM DUAL
    UNION ALL SELECT 'CONTROLS' FROM DUAL
),
MONTH_CRAFTS AS (
    SELECT
        M.PM_MONTH_DATE,
        C.CRAFT
    FROM MONTHS M
    CROSS JOIN CRAFTS C
),
CRAFT_ROLLUP AS (
    SELECT
        PM_MONTH_DATE,
        CRAFT,
        COUNT(DISTINCT WIP_ENTITY_ID) AS PM_WORK_ORDER_COUNT,
        COUNT(*) AS RESOURCE_LINE_COUNT,
        SUM(DOCUMENTED_PM_HOURS) AS DOCUMENTED_PM_HOURS
    FROM PM_RESOURCE_LINES
    WHERE CRAFT IN ('MECHANICAL', 'ELECTRICAL', 'CONTROLS')
    GROUP BY PM_MONTH_DATE, CRAFT
),
UNMAPPED_ROLLUP AS (
    SELECT
        PM_MONTH_DATE,
        COUNT(DISTINCT WIP_ENTITY_ID) AS UNMAPPED_PM_WORK_ORDER_COUNT,
        COUNT(*) AS UNMAPPED_RESOURCE_LINE_COUNT,
        SUM(DOCUMENTED_PM_HOURS) AS UNMAPPED_DOCUMENTED_PM_HOURS
    FROM PM_RESOURCE_LINES
    WHERE CRAFT = 'UNMAPPED'
    GROUP BY PM_MONTH_DATE
)
SELECT
    TO_CHAR(MC.PM_MONTH_DATE, 'YYYY-MM') AS PM_MONTH,
    MC.CRAFT,
    NVL(CR.PM_WORK_ORDER_COUNT, 0) AS PM_WORK_ORDER_COUNT,
    NVL(CR.RESOURCE_LINE_COUNT, 0) AS RESOURCE_LINE_COUNT,
    NVL(CR.DOCUMENTED_PM_HOURS, 0) AS DOCUMENTED_PM_HOURS,
    NVL(UR.UNMAPPED_PM_WORK_ORDER_COUNT, 0) AS UNMAPPED_PM_WORK_ORDER_COUNT_IN_MONTH,
    NVL(UR.UNMAPPED_RESOURCE_LINE_COUNT, 0) AS UNMAPPED_RESOURCE_LINE_COUNT_IN_MONTH,
    NVL(UR.UNMAPPED_DOCUMENTED_PM_HOURS, 0) AS UNMAPPED_DOCUMENTED_PM_HOURS_IN_MONTH
FROM MONTH_CRAFTS MC
LEFT JOIN CRAFT_ROLLUP CR
    ON CR.PM_MONTH_DATE = MC.PM_MONTH_DATE
   AND CR.CRAFT = MC.CRAFT
LEFT JOIN UNMAPPED_ROLLUP UR
    ON UR.PM_MONTH_DATE = MC.PM_MONTH_DATE
ORDER BY
    MC.PM_MONTH_DATE,
    CASE MC.CRAFT
        WHEN 'MECHANICAL' THEN 1
        WHEN 'ELECTRICAL' THEN 2
        WHEN 'CONTROLS' THEN 3
        ELSE 4
    END;

SPOOL OFF
EXIT
