SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    TO_CHAR(TRUNC(EWO.CREATION_DATE, 'MM'), 'YYYY-MM') AS PM_MONTH,
    BR.RESOURCE_CODE,
    BR.DESCRIPTION AS RESOURCE_DESCRIPTION,
    COUNT(DISTINCT EWO.WIP_ENTITY_ID) AS PM_WORK_ORDER_COUNT,
    COUNT(*) AS RESOURCE_LINE_COUNT,
    SUM(NVL(WOR.USAGE_RATE_OR_AMOUNT, 0)) AS DOCUMENTED_PM_HOURS
FROM WIP.WIP_OPERATION_RESOURCES WOR
JOIN APPS.EAM_WORK_ORDERS_V EWO
    ON EWO.WIP_ENTITY_ID = WOR.WIP_ENTITY_ID
   AND EWO.ORGANIZATION_ID = WOR.ORGANIZATION_ID
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
JOIN BOM.BOM_RESOURCES BR
    ON BR.RESOURCE_ID = WOR.RESOURCE_ID
   AND BR.ORGANIZATION_ID = WOR.ORGANIZATION_ID
WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
  AND EWO.CREATION_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -__MONTHS__)
  AND (EWO.WIP_ENTITY_NAME LIKE 'PM%' OR UPPER(NVL(EWO.WORK_ORDER_TYPE_DISP, '')) IN ('PM', 'PREVENTIVE MAINTENANCE'))
  AND BR.UNIT_OF_MEASURE = 'HR'
GROUP BY
    TRUNC(EWO.CREATION_DATE, 'MM'),
    BR.RESOURCE_CODE,
    BR.DESCRIPTION
ORDER BY
    TRUNC(EWO.CREATION_DATE, 'MM'),
    DOCUMENTED_PM_HOURS DESC,
    BR.RESOURCE_CODE;

SPOOL OFF
EXIT
