SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    TO_CHAR(TRUNC(EWO.CREATION_DATE, 'MM'), 'YYYY-MM') AS WORK_ORDER_MONTH,
    BR.RESOURCE_CODE,
    BR.DESCRIPTION AS RESOURCE_DESCRIPTION,
    EWO.WIP_ENTITY_NAME AS WORK_ORDER,
    CASE
        WHEN EWO.WIP_ENTITY_NAME LIKE 'PM%'
          OR UPPER(NVL(EWO.WORK_ORDER_TYPE_DISP, '')) IN ('PM', 'PREVENTIVE MAINTENANCE')
        THEN 'PLANNED'
        ELSE 'REACTIVE'
    END AS MAINTENANCE_SPLIT,
    EWO.WORK_ORDER_STATUS,
    EWO.WORK_ORDER_TYPE_DISP AS WO_TYPE,
    EWO.CLASS_CODE,
    EWO.ASSET_NUMBER,
    EWO.ASSET_DESCRIPTION,
    EWO.ASSET_ACTIVITY,
    EWO.DESCRIPTION AS WORK_ORDER_DESCRIPTION,
    TO_CHAR(EWO.CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS WO_CREATED_DATE,
    TO_CHAR(EWO.SCHEDULED_START_DATE, 'MM/DD/YYYY HH24:MI:SS') AS SCHEDULED_START_DATE,
    WO.OPERATION_SEQ_NUM,
    BD.DEPARTMENT_CODE,
    BD.DESCRIPTION AS DEPARTMENT_DESCRIPTION,
    WO.OPERATION_COMPLETED,
    WOR.RESOURCE_SEQ_NUM,
    NVL(WOR.USAGE_RATE_OR_AMOUNT, 0) AS DOCUMENTED_HOURS,
    NVL(WOR.APPLIED_RESOURCE_UNITS, 0) AS APPLIED_RESOURCE_UNITS,
    BR.UNIT_OF_MEASURE AS RESOURCE_UOM
FROM WIP.WIP_OPERATION_RESOURCES WOR
JOIN APPS.EAM_WORK_ORDERS_V EWO
    ON EWO.WIP_ENTITY_ID = WOR.WIP_ENTITY_ID
   AND EWO.ORGANIZATION_ID = WOR.ORGANIZATION_ID
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
JOIN BOM.BOM_RESOURCES BR
    ON BR.RESOURCE_ID = WOR.RESOURCE_ID
   AND BR.ORGANIZATION_ID = WOR.ORGANIZATION_ID
LEFT JOIN APPS.WIP_OPERATIONS_V WO
    ON WO.WIP_ENTITY_ID = WOR.WIP_ENTITY_ID
   AND WO.ORGANIZATION_ID = WOR.ORGANIZATION_ID
   AND WO.OPERATION_SEQ_NUM = WOR.OPERATION_SEQ_NUM
LEFT JOIN BOM.BOM_DEPARTMENTS BD
    ON BD.DEPARTMENT_ID = WO.DEPARTMENT_ID
   AND BD.ORGANIZATION_ID = WO.ORGANIZATION_ID
WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
  AND EWO.CREATION_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -__MONTHS__)
  AND BR.UNIT_OF_MEASURE = 'HR'
ORDER BY
    BR.RESOURCE_CODE,
    EWO.CREATION_DATE DESC,
    EWO.WIP_ENTITY_NAME,
    WO.OPERATION_SEQ_NUM,
    WOR.RESOURCE_SEQ_NUM;

SPOOL OFF
EXIT
