-- pm_released_work_orders.sql
-- Released PM work orders
-- Output file passed as &1 from SQLcl

SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET DEFINE ON

-- SQLcl CSV formatting (preferred in SQLcl)
SET SQLFORMAT CSV

SPOOL &1

SELECT DISTINCT
    EWO.WIP_ENTITY_NAME,
    TO_CHAR(EWO.CREATION_DATE,'MM/DD/YYYY HH24:MI:SS') AS CREATION_DATE_TIME,
    EWO.ASSET_NUMBER,
    EWO.ASSET_ACTIVITY,
    WO2.DEPARTMENT_CODE,
    EWO.WIP_ENTITY_ID,
    EWO.ASSET_DESCRIPTION,
    EWO.WORK_ORDER_STATUS,
    WO2.OPERATION_SEQ_NUM,
    WO2.OPERATION_COMPLETED,
    SCHEDULED_START_DATE
FROM
    EAM.EAM_PM_SCHEDULING_RULES,
    APPS.WIP_OPERATIONS_V WO1,
    APPS.EAM_WORK_ORDERS_V EWO,
    APPS.MTL_PARAMETERS MP,
    APPS.WIP_OPERATIONS_V WO2
WHERE
    EWO.WIP_ENTITY_ID = WO1.WIP_ENTITY_ID
    AND EWO.WIP_ENTITY_ID = WO2.WIP_ENTITY_ID
    AND EWO.ORGANIZATION_ID = 1169
    AND EWO.ORGANIZATION_ID = MP.ORGANIZATION_ID
    AND WO1.ORGANIZATION_ID = MP.ORGANIZATION_ID
    AND WO1.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    AND WO2.ORGANIZATION_ID = MP.ORGANIZATION_ID
    AND WO2.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    AND WO1.ORGANIZATION_ID = WO2.ORGANIZATION_ID
    AND WO1.WIP_ENTITY_ID = WO2.WIP_ENTITY_ID
    AND MP.ORGANIZATION_CODE = 'XAU'
    AND EWO.WIP_ENTITY_NAME LIKE 'PM%'
    AND EWO.WORK_ORDER_STATUS = 'Released'
    AND EWO.ASSET_NUMBER LIKE 'AU%'
ORDER BY
    CREATION_DATE_TIME ASC;

SPOOL OFF
EXIT
