SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    USER_ID,
    USER_NAME,
    PERSON_NAME,
    EMAIL_ADDRESS,
    GROUP_NAME,
    STATUS,
    LAST_UPDATE_DATE
FROM APPS.QA_USER_GROUP_V
WHERE USER_NAME = __IDENTIFIER__
   OR TO_CHAR(USER_ID) = __IDENTIFIER__
ORDER BY GROUP_NAME;

SPOOL OFF
EXIT
