SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH ALL_PLANS AS (
    SELECT
        MP.ORGANIZATION_CODE,
        QP.PLAN_ID,
        QP.NAME AS PLAN_NAME,
        QP.DESCRIPTION AS PLAN_DESCRIPTION
    FROM QA.QA_PLANS QP
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = QP.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND QP.NAME LIKE __PLAN_NAME_LIKE__
), LOCATION_FIELDS AS (
    SELECT
        QPC.PLAN_ID,
        QPC.CHAR_ID,
        QC.NAME AS ELEMENT_NAME,
        QPC.PROMPT AS FIELD_PROMPT,
        QPC.RESULT_COLUMN_NAME,
        QPC.PROMPT_SEQUENCE,
        QPC.ENABLED_FLAG,
        QPC.DISPLAYED_FLAG,
        QPC.MANDATORY_FLAG
    FROM QA.QA_PLAN_CHARS QPC
    JOIN QA.QA_CHARS QC
        ON QC.CHAR_ID = QPC.CHAR_ID
    WHERE UPPER(QPC.PROMPT) IN ('LOCATION', 'STATION', 'STATIONS')
), LOCATION_VALUES AS (
    SELECT
        QPCVL.PLAN_ID,
        QPCVL.CHAR_ID,
        QPCVL.SHORT_CODE AS LOCATION_VALUE,
        QPCVL.DESCRIPTION AS LOCATION_DESCRIPTION
    FROM QA.QA_PLAN_CHAR_VALUE_LOOKUPS QPCVL
), ASSET_ACTIVITY_TRIGGERS AS (
    SELECT DISTINCT
        QPCT.PLAN_ID,
        QPCT.LOW_VALUE AS ASSET_ACTIVITY,
        QPCT.LOW_VALUE_ID AS ASSET_ACTIVITY_ID,
        QPCT.OPERATOR_MEANING AS ASSET_ACTIVITY_OPERATOR
    FROM APPS.QA_PLAN_COLLECTION_TRIGGERS_V QPCT
    WHERE QPCT.COLLECTION_TRIGGER_DESCRIPTION = 'Asset Activity'
)
SELECT
    AP.ORGANIZATION_CODE,
    AP.PLAN_ID,
    AP.PLAN_NAME,
    REGEXP_REPLACE(AP.PLAN_NAME, '^XAU[[:space:]]+MECH_', '', 1, 1, 'i')
        AS EQUIPMENT_GROUP_FROM_PLAN_NAME,
    AP.PLAN_DESCRIPTION,
    AAT.ASSET_ACTIVITY,
    AAT.ASSET_ACTIVITY_ID,
    AAT.ASSET_ACTIVITY_OPERATOR,
    LF.CHAR_ID,
    LF.ELEMENT_NAME,
    LF.FIELD_PROMPT,
    LF.RESULT_COLUMN_NAME,
    LF.PROMPT_SEQUENCE,
    LF.ENABLED_FLAG AS LOCATION_FIELD_ENABLED,
    LF.DISPLAYED_FLAG AS LOCATION_FIELD_DISPLAYED,
    LF.MANDATORY_FLAG AS LOCATION_FIELD_MANDATORY,
    LV.LOCATION_VALUE,
    LV.LOCATION_DESCRIPTION,
    CASE WHEN LF.PLAN_ID IS NULL THEN 'N' ELSE 'Y' END AS HAS_LOCATION_FIELD,
    CASE WHEN LV.LOCATION_VALUE IS NULL THEN 'N' ELSE 'Y' END AS HAS_LOCATION_VALUE
FROM ALL_PLANS AP
LEFT JOIN ASSET_ACTIVITY_TRIGGERS AAT
    ON AAT.PLAN_ID = AP.PLAN_ID
LEFT JOIN LOCATION_FIELDS LF
    ON LF.PLAN_ID = AP.PLAN_ID
LEFT JOIN LOCATION_VALUES LV
    ON LV.PLAN_ID = LF.PLAN_ID
   AND LV.CHAR_ID = LF.CHAR_ID
ORDER BY
    AP.PLAN_NAME,
    AAT.ASSET_ACTIVITY,
    LF.PROMPT_SEQUENCE,
    LV.LOCATION_VALUE;

SPOOL OFF
EXIT
