SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH ALL_PLANS AS (
    SELECT
        MP.ORGANIZATION_CODE,
        QP.PLAN_ID,
        QP.NAME AS PLAN_NAME,
        REGEXP_REPLACE(QP.NAME, '^XAU[[:space:]]+MECH_', '', 1, 1, 'i')
            AS EQUIPMENT_GROUP_FROM_PLAN_NAME,
        QP.DESCRIPTION AS PLAN_DESCRIPTION
    FROM QA.QA_PLANS QP
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = QP.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND QP.NAME LIKE __PLAN_NAME_LIKE__
), ASSET_ACTIVITY_TRIGGERS AS (
    SELECT DISTINCT
        QPCT.PLAN_ID,
        QPCT.LOW_VALUE AS ASSET_ACTIVITY,
        QPCT.LOW_VALUE_ID AS ASSET_ACTIVITY_ID,
        QPCT.OPERATOR_MEANING AS ASSET_ACTIVITY_OPERATOR
    FROM APPS.QA_PLAN_COLLECTION_TRIGGERS_V QPCT
    WHERE QPCT.COLLECTION_TRIGGER_DESCRIPTION = 'Asset Activity'
), PLAN_ASSETS AS (
    SELECT
        AP.ORGANIZATION_CODE,
        AP.PLAN_ID,
        AAT.ASSET_ACTIVITY,
        EWO.ASSET_NUMBER,
        EWO.ASSET_DESCRIPTION,
        EWO.ASSET_GROUP_ID,
        COUNT(DISTINCT EWO.WIP_ENTITY_ID) AS WORK_ORDER_COUNT_ALL_TIME,
        SUM(CASE WHEN EWO.CREATION_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -12) THEN 1 ELSE 0 END)
            AS WORK_ORDER_COUNT_12MO,
        MIN(EWO.CREATION_DATE) AS FIRST_WORK_ORDER_DATE,
        MAX(EWO.CREATION_DATE) AS LAST_WORK_ORDER_DATE
    FROM ALL_PLANS AP
    JOIN ASSET_ACTIVITY_TRIGGERS AAT
        ON AAT.PLAN_ID = AP.PLAN_ID
    JOIN APPS.EAM_WORK_ORDERS_V EWO
        ON EWO.ASSET_ACTIVITY = AAT.ASSET_ACTIVITY
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
       AND MP.ORGANIZATION_CODE = AP.ORGANIZATION_CODE
    WHERE EWO.ASSET_NUMBER IS NOT NULL
    GROUP BY
        AP.ORGANIZATION_CODE,
        AP.PLAN_ID,
        AAT.ASSET_ACTIVITY,
        EWO.ASSET_NUMBER,
        EWO.ASSET_DESCRIPTION,
        EWO.ASSET_GROUP_ID
)
SELECT
    AP.ORGANIZATION_CODE,
    AP.PLAN_ID,
    AP.PLAN_NAME,
    AP.EQUIPMENT_GROUP_FROM_PLAN_NAME,
    AP.PLAN_DESCRIPTION,
    AAT.ASSET_ACTIVITY,
    AAT.ASSET_ACTIVITY_ID,
    AAT.ASSET_ACTIVITY_OPERATOR,
    PA.ASSET_NUMBER,
    REGEXP_REPLACE(PA.ASSET_NUMBER, '^AU-', '', 1, 1, 'i') AS ASSET_NUMBER_CLEAN,
    PA.ASSET_DESCRIPTION,
    PA.ASSET_GROUP_ID,
    PA.WORK_ORDER_COUNT_ALL_TIME,
    PA.WORK_ORDER_COUNT_12MO,
    TO_CHAR(PA.FIRST_WORK_ORDER_DATE, 'MM/DD/YYYY') AS FIRST_WORK_ORDER_DATE,
    TO_CHAR(PA.LAST_WORK_ORDER_DATE, 'MM/DD/YYYY') AS LAST_WORK_ORDER_DATE,
    CASE WHEN AAT.ASSET_ACTIVITY IS NULL THEN 'N' ELSE 'Y' END AS HAS_ASSET_ACTIVITY_TRIGGER,
    CASE WHEN PA.ASSET_NUMBER IS NULL THEN 'N' ELSE 'Y' END AS HAS_INFERRED_ASSET
FROM ALL_PLANS AP
LEFT JOIN ASSET_ACTIVITY_TRIGGERS AAT
    ON AAT.PLAN_ID = AP.PLAN_ID
LEFT JOIN PLAN_ASSETS PA
    ON PA.ORGANIZATION_CODE = AP.ORGANIZATION_CODE
   AND PA.PLAN_ID = AP.PLAN_ID
   AND PA.ASSET_ACTIVITY = AAT.ASSET_ACTIVITY
ORDER BY
    AP.EQUIPMENT_GROUP_FROM_PLAN_NAME,
    AP.PLAN_NAME,
    AAT.ASSET_ACTIVITY,
    PA.ASSET_NUMBER;

SPOOL OFF
EXIT
