SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    EWO.WIP_ENTITY_NAME AS WORK_ORDER,
    EWO.ASSET_NUMBER,
    EWO.ASSET_DESCRIPTION,
    EWO.ASSET_ACTIVITY,
    EWO.WORK_ORDER_STATUS,
    EWO.WORK_ORDER_TYPE_DISP AS WO_TYPE,
    TO_CHAR(EWO.CREATION_DATE, 'MM/DD/YYYY') AS CREATED,
    TO_CHAR(EWO.SCHEDULED_START_DATE, 'MM/DD/YYYY') AS SCHEDULED_START
FROM APPS.EAM_WORK_ORDERS_V EWO
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
  AND EWO.ASSET_NUMBER = __ASSET_NUMBER__
  AND EWO.WORK_ORDER_STATUS = 'Released'
ORDER BY EWO.CREATION_DATE DESC;

SPOOL OFF
EXIT
