SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    PEO.FULL_NAME,
    BR.RESOURCE_CODE,
    BR.DESCRIPTION AS RESOURCE_DESCRIPTION,
    BR.UNIT_OF_MEASURE,
    BRE.EFFECTIVE_START_DATE,
    BRE.EFFECTIVE_END_DATE
FROM APPS.PER_ALL_PEOPLE_F PEO
JOIN BOM.BOM_RESOURCE_EMPLOYEES BRE
    ON BRE.PERSON_ID = PEO.PERSON_ID
   AND SYSDATE <= BRE.EFFECTIVE_END_DATE
JOIN BOM.BOM_RESOURCES BR
    ON BR.RESOURCE_ID = BRE.RESOURCE_ID
   AND BR.ORGANIZATION_ID = BRE.ORGANIZATION_ID
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = BR.ORGANIZATION_ID
WHERE SYSDATE BETWEEN PEO.EFFECTIVE_START_DATE AND PEO.EFFECTIVE_END_DATE
  AND MP.ORGANIZATION_CODE = __ORG_CODE__
  AND UPPER(PEO.FULL_NAME) LIKE UPPER('%' || __NAME__ || '%')
ORDER BY PEO.FULL_NAME, BR.RESOURCE_CODE;

SPOOL OFF
EXIT
