SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH OP10_DEPT AS (
    SELECT
        WO.ORGANIZATION_ID,
        WO.WIP_ENTITY_ID,
        BD.DEPARTMENT_CODE AS PRIMARY_DEPARTMENT_CODE,
        BD.DESCRIPTION AS PRIMARY_DEPARTMENT_DESCRIPTION
    FROM APPS.WIP_OPERATIONS_V WO
    LEFT JOIN BOM.BOM_DEPARTMENTS BD
        ON BD.DEPARTMENT_ID = WO.DEPARTMENT_ID
       AND BD.ORGANIZATION_ID = WO.ORGANIZATION_ID
    WHERE WO.OPERATION_SEQ_NUM = 10
),
PART_ISSUES AS (
    SELECT
        MMT.TRANSACTION_ID,
        MMT.ORGANIZATION_ID,
        MMT.TRANSACTION_SOURCE_ID AS WIP_ENTITY_ID,
        MMT.INVENTORY_ITEM_ID,
        MMT.TRANSACTION_TYPE_ID,
        MMT.TRANSACTION_DATE,
        MMT.TRANSACTION_QUANTITY,
        ABS(MMT.TRANSACTION_QUANTITY) AS ISSUED_QTY,
        NVL(MMT.TRANSACTION_COST, MMT.ACTUAL_COST) AS UNIT_MATERIAL_COST,
        ABS(MMT.TRANSACTION_QUANTITY) * NVL(MMT.TRANSACTION_COST, MMT.ACTUAL_COST) AS LINE_MATERIAL_COST,
        MMT.TRANSACTION_UOM,
        MMT.SUBINVENTORY_CODE,
        MMT.TRANSACTION_REFERENCE,
        MMT.SOURCE_CODE
    FROM INV.MTL_MATERIAL_TRANSACTIONS MMT
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = MMT.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND MMT.TRANSACTION_SOURCE_TYPE_ID = 5
      AND MMT.TRANSACTION_QUANTITY < 0
      AND MMT.TRANSACTION_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -__MONTHS__)
)
SELECT
    TO_CHAR(TRUNC(PI.TRANSACTION_DATE, 'MM'), 'YYYY-MM') AS SPEND_MONTH,
    TO_CHAR(PI.TRANSACTION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS TRANSACTION_DATE,
    PI.TRANSACTION_ID,
    EWO.WIP_ENTITY_NAME AS WORK_ORDER,
    CASE
        WHEN EWO.WIP_ENTITY_NAME LIKE 'PM%'
          OR UPPER(NVL(EWO.WORK_ORDER_TYPE_DISP, '')) IN ('PM', 'PREVENTIVE MAINTENANCE')
        THEN 'PLANNED'
        ELSE 'REACTIVE'
    END AS MAINTENANCE_SPLIT,
    EWO.WORK_ORDER_STATUS,
    EWO.WORK_ORDER_TYPE_DISP AS WO_TYPE,
    EWO.CLASS_CODE,
    TO_CHAR(EWO.CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS WO_CREATED,
    EWO.ASSET_NUMBER,
    EWO.ASSET_DESCRIPTION,
    EWO.ASSET_ACTIVITY,
    EWO.DESCRIPTION AS WORK_ORDER_DESCRIPTION,
    OP10.PRIMARY_DEPARTMENT_CODE,
    OP10.PRIMARY_DEPARTMENT_DESCRIPTION,
    MSI.SEGMENT1 AS PART_NUMBER,
    MSI.DESCRIPTION AS PART_DESCRIPTION,
    MTT.TRANSACTION_TYPE_NAME AS TRANSACTION_TYPE,
    PI.TRANSACTION_QUANTITY AS RAW_TRANSACTION_QTY,
    PI.ISSUED_QTY,
    PI.UNIT_MATERIAL_COST,
    PI.LINE_MATERIAL_COST,
    PI.TRANSACTION_UOM AS UOM,
    PI.SUBINVENTORY_CODE AS FROM_SUBINVENTORY,
    PI.TRANSACTION_REFERENCE AS REFERENCE,
    PI.SOURCE_CODE
FROM PART_ISSUES PI
JOIN APPS.EAM_WORK_ORDERS_V EWO
    ON EWO.WIP_ENTITY_ID = PI.WIP_ENTITY_ID
   AND EWO.ORGANIZATION_ID = PI.ORGANIZATION_ID
JOIN INV.MTL_SYSTEM_ITEMS_B MSI
    ON MSI.INVENTORY_ITEM_ID = PI.INVENTORY_ITEM_ID
   AND MSI.ORGANIZATION_ID = PI.ORGANIZATION_ID
JOIN INV.MTL_TRANSACTION_TYPES MTT
    ON MTT.TRANSACTION_TYPE_ID = PI.TRANSACTION_TYPE_ID
LEFT JOIN OP10_DEPT OP10
    ON OP10.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND OP10.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
WHERE (__DEPARTMENT_CODE__ = 'ALL' OR OP10.PRIMARY_DEPARTMENT_CODE = __DEPARTMENT_CODE__)
  AND (__ASSET_NUMBER__ = 'ALL' OR EWO.ASSET_NUMBER = __ASSET_NUMBER__)
  AND (__PART_NUMBER__ = 'ALL' OR MSI.SEGMENT1 = __PART_NUMBER__)
  AND (
        __SPLIT__ = 'ALL'
        OR (__SPLIT__ = 'PLANNED' AND (
            EWO.WIP_ENTITY_NAME LIKE 'PM%'
            OR UPPER(NVL(EWO.WORK_ORDER_TYPE_DISP, '')) IN ('PM', 'PREVENTIVE MAINTENANCE')
        ))
        OR (__SPLIT__ = 'REACTIVE' AND NOT (
            EWO.WIP_ENTITY_NAME LIKE 'PM%'
            OR UPPER(NVL(EWO.WORK_ORDER_TYPE_DISP, '')) IN ('PM', 'PREVENTIVE MAINTENANCE')
        ))
      )
ORDER BY
    PI.TRANSACTION_DATE DESC,
    PI.LINE_MATERIAL_COST DESC,
    EWO.WIP_ENTITY_NAME,
    MSI.SEGMENT1;

SPOOL OFF
EXIT
