SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT *
FROM (
    SELECT
        PEO.FULL_NAME AS TECHNICIAN,
        FU.USER_NAME AS BADGE_NUMBER,
        COUNT(QR.ROWID) AS TOTAL_INSPECTIONS,
        COUNT(DISTINCT QR.WORK_ORDER_ID) AS UNIQUE_WORK_ORDERS,
        COUNT(DISTINCT EWO.ASSET_NUMBER) AS UNIQUE_ASSETS,
        MIN(QR.QA_CREATION_DATE) AS FIRST_INSPECTION,
        MAX(QR.QA_CREATION_DATE) AS LAST_INSPECTION
    FROM APPS.QA_RESULTS QR
    JOIN APPS.EAM_WORK_ORDERS_V EWO
        ON EWO.WIP_ENTITY_ID = QR.WORK_ORDER_ID
       AND EWO.ORGANIZATION_ID = QR.ORGANIZATION_ID
    JOIN APPS.FND_USER FU
        ON FU.USER_ID = QR.QA_CREATED_BY
    JOIN APPS.PER_ALL_PEOPLE_F PEO
        ON PEO.PERSON_ID = FU.EMPLOYEE_ID
       AND SYSDATE BETWEEN PEO.EFFECTIVE_START_DATE AND PEO.EFFECTIVE_END_DATE
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = QR.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND QR.QA_CREATION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
    GROUP BY PEO.FULL_NAME, FU.USER_NAME
    ORDER BY TOTAL_INSPECTIONS DESC
)
WHERE ROWNUM <= __LIMIT__;

SPOOL OFF
EXIT
