-- =============================================================
--  Top 10 Assets by Work Order Volume -- Last 12 Months
--
--  NOTE: __ORG_CODE__ is replaced by the Python runner before
--  this file is executed — do not edit that token directly.
--
--  Parameters:
--    &1 = output CSV file path (passed by SQLcl)
-- =============================================================

SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET DEFINE ON
SET SQLFORMAT CSV

SPOOL &1

WITH ORG AS (
    SELECT
        MP.ORGANIZATION_ID,
        MP.ORGANIZATION_CODE,
        HOU.NAME AS ORGANIZATION_NAME
    FROM APPS.MTL_PARAMETERS MP
    JOIN HR.HR_ALL_ORGANIZATION_UNITS HOU
        ON HOU.ORGANIZATION_ID = MP.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = '__ORG_CODE__'
      AND HOU.DATE_TO IS NULL
),
TOP_ASSETS AS (
    SELECT
        EWO.ASSET_NUMBER,
        EWO.ASSET_DESCRIPTION,
        ORG.ORGANIZATION_CODE,
        ORG.ORGANIZATION_NAME,
        ORG.ORGANIZATION_ID,
        COUNT(DISTINCT EWO.WIP_ENTITY_ID)  AS WORK_ORDER_COUNT,
        RANK() OVER (
            ORDER BY COUNT(DISTINCT EWO.WIP_ENTITY_ID) DESC
        )                                   AS ASSET_RANK
    FROM APPS.EAM_WORK_ORDERS_V EWO
    JOIN ORG ON ORG.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    WHERE
        EWO.ASSET_NUMBER  IS NOT NULL
        AND EWO.CREATION_DATE >= ADD_MONTHS(SYSDATE, -12)
    GROUP BY
        EWO.ASSET_NUMBER,
        EWO.ASSET_DESCRIPTION,
        ORG.ORGANIZATION_CODE,
        ORG.ORGANIZATION_NAME,
        ORG.ORGANIZATION_ID
    ORDER BY WORK_ORDER_COUNT DESC
    FETCH FIRST 10 ROWS WITH TIES
)
SELECT
    TA.ORGANIZATION_CODE,
    TA.ORGANIZATION_NAME,
    TA.ASSET_RANK,
    TA.ASSET_NUMBER,
    TA.ASSET_DESCRIPTION,
    TA.WORK_ORDER_COUNT              AS TOTAL_WO_COUNT_12_MONTHS,
    EWO.WIP_ENTITY_NAME              AS WORK_ORDER,
    EWO.WORK_ORDER_STATUS,
    EWO.WORK_ORDER_TYPE_DISP         AS WO_TYPE,
    EWO.ASSET_ACTIVITY,
    TO_CHAR(EWO.CREATION_DATE,
            'MM/DD/YYYY HH24:MI:SS') AS WO_CREATED_DATE,
    TO_CHAR(EWO.SCHEDULED_START_DATE,
            'MM/DD/YYYY')            AS SCHEDULED_START,
    PEO.FULL_NAME                    AS TECHNICIAN,
    FU.USER_NAME                     AS BADGE_NUMBER,
    TO_CHAR(QR.QA_CREATION_DATE,
            'MM/DD/YYYY HH24:MI:SS') AS INSPECTION_DATE,
    QR.MAINTENANCE_OP_SEQ            AS OP_SEQ,
    QR.CHARACTER1                    AS LOT_NUMBER,
    QR.CHARACTER2                    AS LOCATION,
    QR.CHARACTER3                    AS REASON,
    QR.CHARACTER4                    AS ADJUSTMENT,
    QR.COMMENT1                      AS DESCRIPTION,
    EWO.DESCRIPTION                  AS WO_DESCRIPTION
FROM TOP_ASSETS TA
         JOIN APPS.EAM_WORK_ORDERS_V EWO
              ON  EWO.ASSET_NUMBER    = TA.ASSET_NUMBER
                  AND EWO.ORGANIZATION_ID = TA.ORGANIZATION_ID
                  AND EWO.CREATION_DATE  >= ADD_MONTHS(SYSDATE, -12)
         LEFT JOIN APPS.QA_RESULTS QR
                   ON  QR.WORK_ORDER_ID   = EWO.WIP_ENTITY_ID
                       AND QR.ORGANIZATION_ID = EWO.ORGANIZATION_ID
         LEFT JOIN APPS.FND_USER FU
                   ON  FU.USER_ID         = QR.QA_CREATED_BY
         LEFT JOIN APPS.PER_ALL_PEOPLE_F PEO
                   ON  PEO.PERSON_ID      = FU.EMPLOYEE_ID
                       AND SYSDATE BETWEEN PEO.EFFECTIVE_START_DATE
                           AND PEO.EFFECTIVE_END_DATE
ORDER BY
    TA.ASSET_RANK,
    TA.ASSET_NUMBER,
    EWO.CREATION_DATE DESC,
    QR.QA_CREATION_DATE DESC;

SPOOL OFF
EXIT