SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH LATEST_QA AS (
    SELECT
        QR.ORGANIZATION_ID,
        QR.WORK_ORDER_ID,
        PEO.FULL_NAME AS TECHNICIAN,
        FU.USER_NAME AS BADGE_NUMBER,
        TO_CHAR(QR.QA_CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS INSPECTION_DATE,
        ROW_NUMBER() OVER (
            PARTITION BY QR.ORGANIZATION_ID, QR.WORK_ORDER_ID
            ORDER BY QR.QA_CREATION_DATE DESC
        ) AS RN
    FROM APPS.QA_RESULTS QR
    LEFT JOIN APPS.FND_USER FU
        ON FU.USER_ID = QR.QA_CREATED_BY
    LEFT JOIN APPS.PER_ALL_PEOPLE_F PEO
        ON PEO.PERSON_ID = FU.EMPLOYEE_ID
       AND SYSDATE BETWEEN PEO.EFFECTIVE_START_DATE AND PEO.EFFECTIVE_END_DATE
)
SELECT
    EWO.WIP_ENTITY_NAME AS WORK_ORDER,
    EWO.WORK_ORDER_STATUS,
    EWO.WORK_ORDER_TYPE_DISP AS WO_TYPE,
    EWO.ASSET_NUMBER,
    EWO.ASSET_DESCRIPTION,
    TO_CHAR(EWO.CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS WO_CREATED,
    LQ.TECHNICIAN,
    LQ.BADGE_NUMBER,
    LQ.INSPECTION_DATE AS LAST_INSPECTION_DATE,
    MTT.TRANSACTION_TYPE_NAME AS TRANSACTION_TYPE,
    TO_CHAR(MMT.TRANSACTION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS TRANSACTION_DATE,
    MSI.SEGMENT1 AS PART_NUMBER,
    MSI.DESCRIPTION AS PART_DESCRIPTION,
    MMT.TRANSACTION_QUANTITY AS QTY,
    ABS(MMT.TRANSACTION_QUANTITY) AS ABS_QTY,
    NVL(MMT.TRANSACTION_COST, MMT.ACTUAL_COST) AS UNIT_MATERIAL_COST,
    ABS(MMT.TRANSACTION_QUANTITY) * NVL(MMT.TRANSACTION_COST, MMT.ACTUAL_COST) AS LINE_MATERIAL_COST,
    MMT.TRANSACTION_UOM AS UOM,
    MMT.SUBINVENTORY_CODE AS FROM_SUBINVENTORY,
    MMT.TRANSACTION_REFERENCE AS REFERENCE
FROM APPS.EAM_WORK_ORDERS_V EWO
JOIN INV.MTL_MATERIAL_TRANSACTIONS MMT
    ON MMT.TRANSACTION_SOURCE_ID = EWO.WIP_ENTITY_ID
   AND MMT.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND MMT.TRANSACTION_SOURCE_TYPE_ID = 5
JOIN INV.MTL_SYSTEM_ITEMS_B MSI
    ON MSI.INVENTORY_ITEM_ID = MMT.INVENTORY_ITEM_ID
   AND MSI.ORGANIZATION_ID = MMT.ORGANIZATION_ID
JOIN INV.MTL_TRANSACTION_TYPES MTT
    ON MTT.TRANSACTION_TYPE_ID = MMT.TRANSACTION_TYPE_ID
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
LEFT JOIN LATEST_QA LQ
    ON LQ.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND LQ.WORK_ORDER_ID = EWO.WIP_ENTITY_ID
   AND LQ.RN = 1
WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
  AND EWO.WIP_ENTITY_NAME = __WORK_ORDER__
  AND MMT.TRANSACTION_DATE >= SYSDATE - __DAYS__
ORDER BY
    MMT.TRANSACTION_DATE DESC,
    MSI.SEGMENT1;

SPOOL OFF
EXIT
