SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT *
FROM (
    SELECT
        EWO.ASSET_NUMBER,
        EWO.ASSET_DESCRIPTION,
        COUNT(DISTINCT EWO.WIP_ENTITY_ID) AS WORK_ORDER_COUNT,
        COUNT(DISTINCT WT.OPERATION_SEQ_NUM) AS OPERATION_COUNT,
        COUNT(WT.ROWID) AS TIME_TRANSACTION_COUNT,
        SUM(WT.TRANSACTION_QUANTITY) AS TOTAL_TIME_CHARGED_HOURS,
        AVG(WT.TRANSACTION_QUANTITY) AS AVG_TIME_PER_TRANSACTION,
        RANK() OVER (ORDER BY SUM(WT.TRANSACTION_QUANTITY) DESC) AS RANK_BY_TIME_CHARGED
    FROM WIP.WIP_TRANSACTIONS WT
    JOIN APPS.EAM_WORK_ORDERS_V EWO
        ON EWO.WIP_ENTITY_ID = WT.WIP_ENTITY_ID
       AND EWO.ORGANIZATION_ID = WT.ORGANIZATION_ID
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    LEFT JOIN BOM.BOM_RESOURCES BR
        ON BR.RESOURCE_ID = WT.RESOURCE_ID
       AND BR.ORGANIZATION_ID = WT.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND EWO.ASSET_NUMBER IS NOT NULL
      AND EWO.CREATION_DATE >= ADD_MONTHS(SYSDATE, -__MONTHS__)
      AND BR.UNIT_OF_MEASURE = 'HR'
    GROUP BY
        EWO.ASSET_NUMBER,
        EWO.ASSET_DESCRIPTION
    ORDER BY
        TOTAL_TIME_CHARGED_HOURS DESC,
        WORK_ORDER_COUNT DESC,
        EWO.ASSET_NUMBER
)
WHERE ROWNUM <= __LIMIT__;

SPOOL OFF
EXIT
