SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH LATEST_QA AS (
    SELECT
        QR.ORGANIZATION_ID,
        QR.WORK_ORDER_ID,
        PEO.FULL_NAME AS TECHNICIAN,
        FU.USER_NAME AS BADGE_NUMBER,
        TO_CHAR(QR.QA_CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS INSPECTION_DATE,
        ROW_NUMBER() OVER (
            PARTITION BY QR.ORGANIZATION_ID, QR.WORK_ORDER_ID
            ORDER BY QR.QA_CREATION_DATE DESC
        ) AS RN
    FROM APPS.QA_RESULTS QR
    LEFT JOIN APPS.FND_USER FU
        ON FU.USER_ID = QR.QA_CREATED_BY
    LEFT JOIN APPS.PER_ALL_PEOPLE_F PEO
        ON PEO.PERSON_ID = FU.EMPLOYEE_ID
       AND SYSDATE BETWEEN PEO.EFFECTIVE_START_DATE AND PEO.EFFECTIVE_END_DATE
),
WO_PARTS AS (
    SELECT
        EWO.ORGANIZATION_ID,
        EWO.WIP_ENTITY_ID,
        EWO.WIP_ENTITY_NAME AS WORK_ORDER,
        EWO.WORK_ORDER_STATUS,
        EWO.WORK_ORDER_TYPE_DISP AS WO_TYPE,
        EWO.ASSET_NUMBER,
        EWO.ASSET_DESCRIPTION,
        TO_CHAR(EWO.CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS WO_CREATED,
        COUNT(MMT.TRANSACTION_ID) AS PART_TRANSACTIONS,
        COUNT(DISTINCT MMT.INVENTORY_ITEM_ID) AS DISTINCT_PARTS_USED,
        SUM(CASE
                WHEN MMT.TRANSACTION_QUANTITY < 0
                THEN ABS(MMT.TRANSACTION_QUANTITY)
                ELSE 0
            END) AS TOTAL_PARTS_USED,
        SUM(CASE
                WHEN MMT.TRANSACTION_QUANTITY < 0
                THEN ABS(MMT.TRANSACTION_QUANTITY) * NVL(MMT.TRANSACTION_COST, MMT.ACTUAL_COST)
                ELSE 0
            END) AS TOTAL_MATERIAL_COST
    FROM APPS.EAM_WORK_ORDERS_V EWO
    JOIN INV.MTL_MATERIAL_TRANSACTIONS MMT
        ON MMT.TRANSACTION_SOURCE_ID = EWO.WIP_ENTITY_ID
       AND MMT.ORGANIZATION_ID = EWO.ORGANIZATION_ID
       AND MMT.TRANSACTION_SOURCE_TYPE_ID = 5
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND MMT.TRANSACTION_DATE >= SYSDATE - __DAYS__
    GROUP BY
        EWO.ORGANIZATION_ID,
        EWO.WIP_ENTITY_ID,
        EWO.WIP_ENTITY_NAME,
        EWO.WORK_ORDER_STATUS,
        EWO.WORK_ORDER_TYPE_DISP,
        EWO.ASSET_NUMBER,
        EWO.ASSET_DESCRIPTION,
        TO_CHAR(EWO.CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS')
)
SELECT *
FROM (
    SELECT
        WP.WORK_ORDER,
        WP.WORK_ORDER_STATUS,
        WP.WO_TYPE,
        WP.ASSET_NUMBER,
        WP.ASSET_DESCRIPTION,
        WP.WO_CREATED,
        LQ.TECHNICIAN,
        LQ.BADGE_NUMBER,
        LQ.INSPECTION_DATE AS LAST_INSPECTION_DATE,
        WP.PART_TRANSACTIONS,
        WP.DISTINCT_PARTS_USED,
        WP.TOTAL_PARTS_USED,
        WP.TOTAL_MATERIAL_COST
    FROM WO_PARTS WP
    LEFT JOIN LATEST_QA LQ
        ON LQ.ORGANIZATION_ID = WP.ORGANIZATION_ID
       AND LQ.WORK_ORDER_ID = WP.WIP_ENTITY_ID
       AND LQ.RN = 1
    ORDER BY
        WP.PART_TRANSACTIONS DESC,
        WP.TOTAL_MATERIAL_COST DESC,
        WP.TOTAL_PARTS_USED DESC,
        WP.WORK_ORDER
)
WHERE ROWNUM <= __LIMIT__;

SPOOL OFF
EXIT
