SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT *
FROM (
    SELECT
        EWO.WIP_ENTITY_NAME,
        EWO.ASSET_NUMBER,
        COUNT(MMT.TRANSACTION_ID) AS PART_TRANSACTIONS
    FROM APPS.EAM_WORK_ORDERS_V EWO
    JOIN INV.MTL_MATERIAL_TRANSACTIONS MMT
        ON MMT.TRANSACTION_SOURCE_ID = EWO.WIP_ENTITY_ID
       AND MMT.ORGANIZATION_ID = EWO.ORGANIZATION_ID
       AND MMT.TRANSACTION_SOURCE_TYPE_ID = 5
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND MMT.TRANSACTION_DATE >= SYSDATE - __DAYS__
    GROUP BY EWO.WIP_ENTITY_NAME, EWO.ASSET_NUMBER
    ORDER BY PART_TRANSACTIONS DESC
)
WHERE ROWNUM <= __LIMIT__;

SPOOL OFF
EXIT
