SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    FU.USER_ID,
    FU.USER_NAME,
    FU.DESCRIPTION AS FULL_NAME,
    FU.EMAIL_ADDRESS,
    FU.EMPLOYEE_ID AS PERSON_ID,
    PEO.EMPLOYEE_NUMBER,
    PEO.FULL_NAME AS HR_FULL_NAME,
    FRT.RESPONSIBILITY_NAME,
    FA.APPLICATION_SHORT_NAME,
    FUR.START_DATE,
    FUR.END_DATE
FROM APPS.PER_ALL_PEOPLE_F PEO
JOIN APPS.FND_USER FU
    ON FU.EMPLOYEE_ID = PEO.PERSON_ID
LEFT JOIN APPS.FND_USER_RESP_GROUPS_DIRECT FUR
    ON FU.USER_ID = FUR.USER_ID
LEFT JOIN APPS.FND_RESPONSIBILITY FR
    ON FR.RESPONSIBILITY_ID = FUR.RESPONSIBILITY_ID
LEFT JOIN APPS.FND_RESPONSIBILITY_TL FRT
    ON FR.RESPONSIBILITY_ID = FRT.RESPONSIBILITY_ID
   AND FRT.LANGUAGE = 'US'
LEFT JOIN APPS.FND_APPLICATION FA
    ON FR.APPLICATION_ID = FA.APPLICATION_ID
WHERE PEO.EMPLOYEE_NUMBER = __EMPLOYEE_NUMBER__
  AND SYSDATE BETWEEN PEO.EFFECTIVE_START_DATE AND PEO.EFFECTIVE_END_DATE
  AND FA.APPLICATION_SHORT_NAME = __APP_SHORT_NAME__
ORDER BY
    CASE WHEN FUR.END_DATE IS NULL THEN 0 ELSE 1 END,
    FRT.RESPONSIBILITY_NAME;

SPOOL OFF
EXIT
