SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    FU.USER_ID,
    FU.USER_NAME,
    FU.DESCRIPTION AS FULL_NAME,
    FU.EMAIL_ADDRESS,
    FU.EMPLOYEE_ID,
    FRT.RESPONSIBILITY_NAME,
    FA.APPLICATION_SHORT_NAME,
    FUR.START_DATE,
    FUR.END_DATE
FROM APPS.FND_USER FU
LEFT JOIN APPS.FND_USER_RESP_GROUPS_DIRECT FUR
    ON FU.USER_ID = FUR.USER_ID
LEFT JOIN APPS.FND_RESPONSIBILITY FR
    ON FR.RESPONSIBILITY_ID = FUR.RESPONSIBILITY_ID
LEFT JOIN APPS.FND_RESPONSIBILITY_TL FRT
    ON FR.RESPONSIBILITY_ID = FRT.RESPONSIBILITY_ID
   AND FRT.LANGUAGE = 'US'
LEFT JOIN APPS.FND_APPLICATION FA
    ON FR.APPLICATION_ID = FA.APPLICATION_ID
WHERE FU.USER_NAME = __IDENTIFIER__
   OR TO_CHAR(FU.USER_ID) = __IDENTIFIER__
   OR TO_CHAR(FU.EMPLOYEE_ID) = __IDENTIFIER__
ORDER BY FRT.RESPONSIBILITY_NAME;

SPOOL OFF
EXIT
