SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    FU.USER_NAME,
    FU.DESCRIPTION AS FULL_NAME,
    FU.EMAIL_ADDRESS,
    FUR.START_DATE,
    FUR.END_DATE
FROM APPS.FND_USER FU
JOIN APPS.FND_USER_RESP_GROUPS_DIRECT FUR
    ON FUR.USER_ID = FU.USER_ID
JOIN APPS.FND_RESPONSIBILITY FR
    ON FR.RESPONSIBILITY_ID = FUR.RESPONSIBILITY_ID
JOIN APPS.FND_RESPONSIBILITY_TL FRT
    ON FRT.RESPONSIBILITY_ID = FR.RESPONSIBILITY_ID
   AND FRT.LANGUAGE = 'US'
JOIN APPS.FND_APPLICATION FA
    ON FA.APPLICATION_ID = FR.APPLICATION_ID
WHERE FRT.RESPONSIBILITY_NAME = __RESPONSIBILITY_NAME__
  AND FA.APPLICATION_SHORT_NAME = __APP_SHORT_NAME__
  AND (FU.END_DATE IS NULL OR FU.END_DATE > SYSDATE)
ORDER BY FU.USER_NAME;

SPOOL OFF
EXIT
