SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    EWO.WIP_ENTITY_NAME AS WORK_ORDER,
    EWO.WORK_ORDER_STATUS,
    EWO.ASSET_NUMBER,
    EWO.ASSET_DESCRIPTION,
    WT.OPERATION_SEQ_NUM,
    BD.DEPARTMENT_CODE,
    BD.DESCRIPTION AS DEPARTMENT_DESCRIPTION,
    BR.RESOURCE_CODE,
    BR.DESCRIPTION AS RESOURCE_DESCRIPTION,
    BR.UNIT_OF_MEASURE AS RESOURCE_UOM,
    WOR.USAGE_RATE_OR_AMOUNT AS PLANNED_QTY,
    WOR.APPLIED_RESOURCE_UNITS AS APPLIED_QTY,
    SUM(WT.TRANSACTION_QUANTITY) AS CHARGED_TIME_QTY
FROM WIP.WIP_TRANSACTIONS WT
JOIN APPS.EAM_WORK_ORDERS_V EWO
    ON EWO.WIP_ENTITY_ID = WT.WIP_ENTITY_ID
   AND EWO.ORGANIZATION_ID = WT.ORGANIZATION_ID
JOIN APPS.WIP_OPERATIONS_V WO
    ON WO.WIP_ENTITY_ID = WT.WIP_ENTITY_ID
   AND WO.ORGANIZATION_ID = WT.ORGANIZATION_ID
   AND WO.OPERATION_SEQ_NUM = WT.OPERATION_SEQ_NUM
LEFT JOIN BOM.BOM_DEPARTMENTS BD
    ON BD.DEPARTMENT_ID = WO.DEPARTMENT_ID
   AND BD.ORGANIZATION_ID = WO.ORGANIZATION_ID
LEFT JOIN BOM.BOM_RESOURCES BR
    ON BR.RESOURCE_ID = WT.RESOURCE_ID
   AND BR.ORGANIZATION_ID = WT.ORGANIZATION_ID
LEFT JOIN WIP.WIP_OPERATION_RESOURCES WOR
    ON WOR.WIP_ENTITY_ID = WT.WIP_ENTITY_ID
   AND WOR.ORGANIZATION_ID = WT.ORGANIZATION_ID
   AND WOR.OPERATION_SEQ_NUM = WT.OPERATION_SEQ_NUM
   AND WOR.RESOURCE_SEQ_NUM = WT.RESOURCE_SEQ_NUM
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
  AND EWO.WIP_ENTITY_NAME = __WORK_ORDER__
  AND WT.OPERATION_SEQ_NUM = __OPERATION_SEQ__
GROUP BY
    EWO.WIP_ENTITY_NAME,
    EWO.WORK_ORDER_STATUS,
    EWO.ASSET_NUMBER,
    EWO.ASSET_DESCRIPTION,
    WT.OPERATION_SEQ_NUM,
    BD.DEPARTMENT_CODE,
    BD.DESCRIPTION,
    BR.RESOURCE_CODE,
    BR.DESCRIPTION,
    BR.UNIT_OF_MEASURE,
    WOR.USAGE_RATE_OR_AMOUNT,
    WOR.APPLIED_RESOURCE_UNITS
ORDER BY
    WT.OPERATION_SEQ_NUM,
    BD.DEPARTMENT_CODE,
    BR.RESOURCE_CODE;

SPOOL OFF
EXIT
