SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    EWO.WIP_ENTITY_NAME AS WORK_ORDER,
    EWO.ASSET_NUMBER,
    EWO.ASSET_DESCRIPTION,
    EWO.WORK_ORDER_STATUS,
    EWO.WORK_ORDER_TYPE_DISP AS WO_TYPE,
    BD.DEPARTMENT_CODE,
    BD.DESCRIPTION AS DEPARTMENT_DESCRIPTION,
    WO.OPERATION_SEQ_NUM AS OP_SEQ,
    WO.OPERATION_COMPLETED,
    TO_CHAR(EWO.CREATION_DATE, 'MM/DD/YYYY') AS CREATED,
    TO_CHAR(EWO.SCHEDULED_START_DATE, 'MM/DD/YYYY') AS SCHEDULED_START
FROM APPS.EAM_WORK_ORDERS_V EWO
JOIN APPS.WIP_OPERATIONS_V WO
    ON WO.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
   AND WO.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND WO.OPERATION_SEQ_NUM = 10
JOIN BOM.BOM_DEPARTMENTS BD
    ON BD.DEPARTMENT_ID = WO.DEPARTMENT_ID
   AND BD.ORGANIZATION_ID = WO.ORGANIZATION_ID
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
  AND BD.DEPARTMENT_CODE = __DEPARTMENT_CODE__
  AND EWO.CREATION_DATE >= SYSDATE - __DAYS__
ORDER BY EWO.CREATION_DATE DESC;

SPOOL OFF
EXIT
