SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    EWO.WIP_ENTITY_NAME AS WORK_ORDER,
    EWO.ASSET_NUMBER,
    WO.OPERATION_SEQ_NUM AS OP_SEQ,
    BD.DEPARTMENT_CODE,
    BD.DESCRIPTION AS DEPARTMENT_DESCRIPTION,
    WO.OPERATION_COMPLETED,
    WO.LAST_UPDATE_DATE
FROM APPS.EAM_WORK_ORDERS_V EWO
JOIN APPS.WIP_OPERATIONS_V WO
    ON WO.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
   AND WO.ORGANIZATION_ID = EWO.ORGANIZATION_ID
JOIN BOM.BOM_DEPARTMENTS BD
    ON BD.DEPARTMENT_ID = WO.DEPARTMENT_ID
   AND BD.ORGANIZATION_ID = WO.ORGANIZATION_ID
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
  AND EWO.WIP_ENTITY_NAME = __WORK_ORDER__
ORDER BY WO.OPERATION_SEQ_NUM;

SPOOL OFF
EXIT
