SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

SELECT
    EWO.WIP_ENTITY_NAME AS WORK_ORDER,
    EWO.WORK_ORDER_STATUS,
    EWO.WORK_ORDER_TYPE_DISP AS WO_TYPE,
    EWO.ASSET_NUMBER,
    EWO.ASSET_DESCRIPTION,
    EWO.ASSET_ACTIVITY,
    TO_CHAR(EWO.CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS WO_CREATED,
    TO_CHAR(EWO.SCHEDULED_START_DATE, 'MM/DD/YYYY') AS SCHEDULED_START,
    WO.OPERATION_SEQ_NUM AS OP_SEQ,
    WO.OPERATION_COMPLETED,
    BD.DEPARTMENT_CODE,
    PEO.FULL_NAME AS TECHNICIAN,
    FU.USER_NAME AS BADGE_NUMBER,
    TO_CHAR(QR.QA_CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS INSPECTION_DATE,
    QR.CHARACTER1 AS LOT_NUMBER,
    QR.CHARACTER2 AS LOCATION,
    QR.CHARACTER3 AS REASON,
    QR.CHARACTER4 AS ADJUSTMENT,
    QR.COMMENT1 AS DESCRIPTION,
    MSI.SEGMENT1 AS PART_NUMBER,
    MSI.DESCRIPTION AS PART_DESCRIPTION,
    MMT.TRANSACTION_QUANTITY AS PARTS_QTY,
    MMT.TRANSACTION_UOM AS PARTS_UOM,
    MTT.TRANSACTION_TYPE_NAME AS PARTS_TRANSACTION_TYPE
FROM APPS.EAM_WORK_ORDERS_V EWO
LEFT JOIN APPS.WIP_OPERATIONS_V WO
    ON WO.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
   AND WO.ORGANIZATION_ID = EWO.ORGANIZATION_ID
LEFT JOIN BOM.BOM_DEPARTMENTS BD
    ON BD.DEPARTMENT_ID = WO.DEPARTMENT_ID
   AND BD.ORGANIZATION_ID = WO.ORGANIZATION_ID
LEFT JOIN APPS.QA_RESULTS QR
    ON QR.WORK_ORDER_ID = EWO.WIP_ENTITY_ID
   AND QR.ORGANIZATION_ID = EWO.ORGANIZATION_ID
LEFT JOIN APPS.FND_USER FU
    ON FU.USER_ID = QR.QA_CREATED_BY
LEFT JOIN APPS.PER_ALL_PEOPLE_F PEO
    ON PEO.PERSON_ID = FU.EMPLOYEE_ID
   AND SYSDATE BETWEEN PEO.EFFECTIVE_START_DATE AND PEO.EFFECTIVE_END_DATE
LEFT JOIN INV.MTL_MATERIAL_TRANSACTIONS MMT
    ON MMT.TRANSACTION_SOURCE_ID = EWO.WIP_ENTITY_ID
   AND MMT.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND MMT.TRANSACTION_SOURCE_TYPE_ID = 5
LEFT JOIN INV.MTL_SYSTEM_ITEMS_B MSI
    ON MSI.INVENTORY_ITEM_ID = MMT.INVENTORY_ITEM_ID
   AND MSI.ORGANIZATION_ID = MMT.ORGANIZATION_ID
LEFT JOIN INV.MTL_TRANSACTION_TYPES MTT
    ON MTT.TRANSACTION_TYPE_ID = MMT.TRANSACTION_TYPE_ID
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
  AND EWO.WIP_ENTITY_NAME = __WORK_ORDER__
ORDER BY WO.OPERATION_SEQ_NUM, QR.QA_CREATION_DATE DESC, MMT.TRANSACTION_DATE DESC;

SPOOL OFF
EXIT
