SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH OP10_DEPT AS (
    SELECT
        WO.ORGANIZATION_ID,
        WO.WIP_ENTITY_ID,
        BD.DEPARTMENT_CODE AS PRIMARY_DEPARTMENT_CODE,
        BD.DESCRIPTION AS PRIMARY_DEPARTMENT_DESCRIPTION,
        WO.OPERATION_COMPLETED AS OP10_COMPLETED,
        WO.LAST_UPDATE_DATE AS OP10_LAST_UPDATE_DATE
    FROM APPS.WIP_OPERATIONS_V WO
    LEFT JOIN BOM.BOM_DEPARTMENTS BD
        ON BD.DEPARTMENT_ID = WO.DEPARTMENT_ID
       AND BD.ORGANIZATION_ID = WO.ORGANIZATION_ID
    WHERE WO.OPERATION_SEQ_NUM = 10
),
TIME_ROLLUP AS (
    SELECT
        EWO.ORGANIZATION_ID,
        EWO.WIP_ENTITY_ID,
        SUM(WOR.USAGE_RATE_OR_AMOUNT) AS PLANNED_HOURS,
        SUM(WOR.APPLIED_RESOURCE_UNITS) AS APPLIED_HOURS
    FROM APPS.EAM_WORK_ORDERS_V EWO
    JOIN WIP.WIP_OPERATION_RESOURCES WOR
        ON WOR.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
       AND WOR.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    LEFT JOIN BOM.BOM_RESOURCES BR
        ON BR.RESOURCE_ID = WOR.RESOURCE_ID
       AND BR.ORGANIZATION_ID = WOR.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND EWO.CREATION_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -__MONTHS__)
      AND BR.UNIT_OF_MEASURE = 'HR'
    GROUP BY
        EWO.ORGANIZATION_ID,
        EWO.WIP_ENTITY_ID
),
PART_ROLLUP AS (
    SELECT
        EWO.ORGANIZATION_ID,
        EWO.WIP_ENTITY_ID,
        COUNT(MMT.TRANSACTION_ID) AS PART_TRANSACTION_COUNT,
        COUNT(DISTINCT MMT.INVENTORY_ITEM_ID) AS DISTINCT_PARTS_USED,
        SUM(ABS(MMT.TRANSACTION_QUANTITY)) AS TOTAL_PARTS_CONSUMED,
        SUM(ABS(MMT.TRANSACTION_QUANTITY) * NVL(MMT.TRANSACTION_COST, MMT.ACTUAL_COST)) AS TOTAL_MATERIAL_COST
    FROM APPS.EAM_WORK_ORDERS_V EWO
    JOIN INV.MTL_MATERIAL_TRANSACTIONS MMT
        ON MMT.TRANSACTION_SOURCE_ID = EWO.WIP_ENTITY_ID
       AND MMT.ORGANIZATION_ID = EWO.ORGANIZATION_ID
       AND MMT.TRANSACTION_SOURCE_TYPE_ID = 5
       AND MMT.TRANSACTION_QUANTITY < 0
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
    WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
      AND EWO.CREATION_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -__MONTHS__)
    GROUP BY
        EWO.ORGANIZATION_ID,
        EWO.WIP_ENTITY_ID
)
SELECT
    EWO.WIP_ENTITY_NAME AS WORK_ORDER,
    CASE
        WHEN EWO.WIP_ENTITY_NAME LIKE 'PM%'
          OR UPPER(NVL(EWO.WORK_ORDER_TYPE_DISP, '')) IN ('PM', 'PREVENTIVE MAINTENANCE')
        THEN 'PLANNED'
        WHEN UPPER(NVL(EWO.WORK_ORDER_TYPE_DISP, '')) = 'DM'
        THEN 'REACTIVE'
        ELSE 'REACTIVE'
    END AS MAINTENANCE_SPLIT,
    CASE
        WHEN EWO.WIP_ENTITY_NAME LIKE 'PM%' THEN 'WORK_ORDER_PREFIX_PM'
        WHEN UPPER(NVL(EWO.WORK_ORDER_TYPE_DISP, '')) IN ('PM', 'PREVENTIVE MAINTENANCE') THEN 'WORK_ORDER_TYPE_PM'
        WHEN UPPER(NVL(EWO.WORK_ORDER_TYPE_DISP, '')) = 'DM' THEN 'WORK_ORDER_TYPE_DM'
        ELSE 'NOT_PM_OR_PLANNED_TYPE'
    END AS SPLIT_REASON,
    TO_CHAR(TRUNC(EWO.CREATION_DATE, 'MM'), 'YYYY-MM') AS CREATED_MONTH,
    EWO.WORK_ORDER_STATUS,
    EWO.WORK_ORDER_TYPE_DISP AS WO_TYPE,
    EWO.CLASS_CODE,
    EWO.ASSET_NUMBER,
    EWO.ASSET_DESCRIPTION,
    EWO.ASSET_ACTIVITY,
    EWO.DESCRIPTION AS WORK_ORDER_DESCRIPTION,
    OP10.PRIMARY_DEPARTMENT_CODE,
    OP10.PRIMARY_DEPARTMENT_DESCRIPTION,
    OP10.OP10_COMPLETED,
    TO_CHAR(EWO.CREATION_DATE, 'MM/DD/YYYY HH24:MI:SS') AS CREATED_DATE,
    TO_CHAR(EWO.SCHEDULED_START_DATE, 'MM/DD/YYYY HH24:MI:SS') AS SCHEDULED_START_DATE,
    TO_CHAR(OP10.OP10_LAST_UPDATE_DATE, 'MM/DD/YYYY HH24:MI:SS') AS OP10_LAST_UPDATE_DATE,
    NVL(TR.PLANNED_HOURS, 0) AS PLANNED_HOURS,
    NVL(TR.APPLIED_HOURS, 0) AS APPLIED_HOURS,
    NVL(PR.PART_TRANSACTION_COUNT, 0) AS PART_TRANSACTION_COUNT,
    NVL(PR.DISTINCT_PARTS_USED, 0) AS DISTINCT_PARTS_USED,
    NVL(PR.TOTAL_PARTS_CONSUMED, 0) AS TOTAL_PARTS_CONSUMED,
    NVL(PR.TOTAL_MATERIAL_COST, 0) AS TOTAL_MATERIAL_COST
FROM APPS.EAM_WORK_ORDERS_V EWO
JOIN APPS.MTL_PARAMETERS MP
    ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
LEFT JOIN OP10_DEPT OP10
    ON OP10.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND OP10.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
LEFT JOIN TIME_ROLLUP TR
    ON TR.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND TR.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
LEFT JOIN PART_ROLLUP PR
    ON PR.ORGANIZATION_ID = EWO.ORGANIZATION_ID
   AND PR.WIP_ENTITY_ID = EWO.WIP_ENTITY_ID
WHERE MP.ORGANIZATION_CODE = __ORG_CODE__
  AND EWO.CREATION_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -__MONTHS__)
  AND (__DEPARTMENT_CODE__ = 'ALL' OR OP10.PRIMARY_DEPARTMENT_CODE = __DEPARTMENT_CODE__)
  AND (__ASSET_NUMBER__ = 'ALL' OR EWO.ASSET_NUMBER = __ASSET_NUMBER__)
  AND (
        __SPLIT__ = 'ALL'
        OR (__SPLIT__ = 'PLANNED' AND (
            EWO.WIP_ENTITY_NAME LIKE 'PM%'
            OR UPPER(NVL(EWO.WORK_ORDER_TYPE_DISP, '')) IN ('PM', 'PREVENTIVE MAINTENANCE')
        ))
        OR (__SPLIT__ = 'REACTIVE' AND NOT (
            EWO.WIP_ENTITY_NAME LIKE 'PM%'
            OR UPPER(NVL(EWO.WORK_ORDER_TYPE_DISP, '')) IN ('PM', 'PREVENTIVE MAINTENANCE')
        ))
      )
ORDER BY
    EWO.CREATION_DATE DESC,
    EWO.WIP_ENTITY_NAME DESC;

SPOOL OFF
EXIT
