SET ECHO OFF
SET FEEDBACK OFF
SET HEADING ON
SET PAGESIZE 0
SET LINESIZE 32767
SET TERMOUT OFF
SET VERIFY OFF
SET SQLFORMAT CSV

SPOOL &1

WITH PLAN_ACTIVITY AS (
    SELECT DISTINCT
        QP.PLAN_ID,
        QP.NAME AS PLAN_NAME,
        QP.DESCRIPTION AS PLAN_DESCRIPTION,
        MP.ORGANIZATION_CODE,
        QPCT.LOW_VALUE AS ASSET_ACTIVITY,
        QPCT.LOW_VALUE_ID AS ASSET_ACTIVITY_ID
    FROM QA.QA_PLANS QP
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = QP.ORGANIZATION_ID
    JOIN APPS.QA_PLAN_COLLECTION_TRIGGERS_V QPCT
        ON QPCT.PLAN_ID = QP.PLAN_ID
    WHERE MP.ORGANIZATION_CODE = 'XAU'
      AND QP.NAME LIKE 'XAU MECH_%'
      AND QPCT.COLLECTION_TRIGGER_DESCRIPTION = 'Asset Activity'
      AND QPCT.OPERATOR_MEANING = 'equals'
), PLAN_LOCATIONS AS (
    SELECT DISTINCT
        QP.PLAN_ID,
        QPC.CHAR_ID,
        QC.NAME AS ELEMENT_NAME,
        QPC.PROMPT AS FIELD_PROMPT,
        QPC.RESULT_COLUMN_NAME,
        QPCVL.SHORT_CODE AS LOCATION_VALUE,
        QPCVL.DESCRIPTION AS LOCATION_DESCRIPTION
    FROM QA.QA_PLANS QP
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = QP.ORGANIZATION_ID
    JOIN QA.QA_PLAN_CHARS QPC
        ON QPC.PLAN_ID = QP.PLAN_ID
    JOIN QA.QA_CHARS QC
        ON QC.CHAR_ID = QPC.CHAR_ID
    JOIN QA.QA_PLAN_CHAR_VALUE_LOOKUPS QPCVL
        ON QPCVL.PLAN_ID = QPC.PLAN_ID
       AND QPCVL.CHAR_ID = QPC.CHAR_ID
    WHERE MP.ORGANIZATION_CODE = 'XAU'
      AND QP.NAME LIKE 'XAU MECH_%'
      AND UPPER(QPC.PROMPT) = 'LOCATION'
      AND QPC.ENABLED_FLAG = 1
), PLAN_ASSETS AS (
    SELECT
        PA.ORGANIZATION_CODE,
        PA.PLAN_ID,
        PA.PLAN_NAME,
        PA.PLAN_DESCRIPTION,
        PA.ASSET_ACTIVITY,
        EWO.ASSET_NUMBER,
        EWO.ASSET_DESCRIPTION,
        EWO.ASSET_GROUP_ID,
        COUNT(DISTINCT EWO.WIP_ENTITY_ID) AS WORK_ORDER_COUNT_ALL_TIME,
        SUM(CASE WHEN EWO.CREATION_DATE >= ADD_MONTHS(TRUNC(SYSDATE), -12) THEN 1 ELSE 0 END) AS WORK_ORDER_COUNT_12MO,
        MIN(EWO.CREATION_DATE) AS FIRST_WORK_ORDER_DATE,
        MAX(EWO.CREATION_DATE) AS LAST_WORK_ORDER_DATE
    FROM PLAN_ACTIVITY PA
    JOIN APPS.EAM_WORK_ORDERS_V EWO
        ON EWO.ASSET_ACTIVITY = PA.ASSET_ACTIVITY
    JOIN APPS.MTL_PARAMETERS MP
        ON MP.ORGANIZATION_ID = EWO.ORGANIZATION_ID
       AND MP.ORGANIZATION_CODE = PA.ORGANIZATION_CODE
    WHERE EWO.ASSET_NUMBER IS NOT NULL
    GROUP BY
        PA.ORGANIZATION_CODE,
        PA.PLAN_ID,
        PA.PLAN_NAME,
        PA.PLAN_DESCRIPTION,
        PA.ASSET_ACTIVITY,
        EWO.ASSET_NUMBER,
        EWO.ASSET_DESCRIPTION,
        EWO.ASSET_GROUP_ID
)
SELECT
    PA.ORGANIZATION_CODE,
    PA.ASSET_NUMBER,
    PA.ASSET_DESCRIPTION,
    PA.ASSET_ACTIVITY,
    PA.PLAN_ID,
    PA.PLAN_NAME,
    PL.LOCATION_VALUE,
    PL.LOCATION_DESCRIPTION,
    PL.RESULT_COLUMN_NAME,
    PA.WORK_ORDER_COUNT_ALL_TIME,
    PA.WORK_ORDER_COUNT_12MO,
    TO_CHAR(PA.FIRST_WORK_ORDER_DATE, 'MM/DD/YYYY') AS FIRST_WORK_ORDER_DATE,
    TO_CHAR(PA.LAST_WORK_ORDER_DATE, 'MM/DD/YYYY') AS LAST_WORK_ORDER_DATE
FROM PLAN_ASSETS PA
JOIN PLAN_LOCATIONS PL
    ON PL.PLAN_ID = PA.PLAN_ID
ORDER BY PA.ASSET_NUMBER, PA.PLAN_NAME, PL.LOCATION_VALUE;

SPOOL OFF
EXIT
